<a href="https://colab.research.google.com/github/MarcosVCS/Projeto-Final---Engenharia-de-Dados---SoulCode/blob/main/COEXP_ana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1 - instalar e importar

In [ ]:
import pandas as pd

In [ ]:
#Configurações de numero maximo de colunas em exibição
pd.set_option('display.max_columns',30)

In [ ]:
import numpy as np

google

In [ ]:
#instalar o gc file system
!pip install gcsfs

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#importar a liberação da chave de acesso
import os
serviceAccount =  '/content/aula-bc26-flavia-75af138d1cdd.json'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

In [ ]:
from google.cloud import storage

In [ ]:
from google.cloud.storage.blob import Blob 
import requests

In [ ]:
from google.oauth2 import service_account 
import os
import pandas_gbq 

from IPython.display import clear_output

spark

In [ ]:
pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 KB 15.9 MB/s eta 0:00:00
  Created wheel for pyspark: filename=pyspark-3.3.1-py2.py3-none-any.whl size=281845512 sha256=094f13b28ca49b1949f4be0c4b9f0325c1a40491555645b7deba995065476708
  Stored in directory: /root/.cache/pip/wheels/43/dc/11/ec201cd671da62fa9c5cc77078235e40722170ceba231d7598
Successfully built pyspark


In [ ]:
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.sql.types import *
from pyspark.sql.window import Window

In [ ]:
spark = (
    SparkSession.builder
    .master('local')
    .appName('data-frames')
    .config('spark.ui.port','4050')
    .config('spark.jars', 'https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop2-latest.jar')
    .getOrCreate()
)

In [ ]:
spark

#2 - Conector Goggle Storage

In [ ]:
# Upload do ARQUIVO DO BUCKET - Ana

# Chave de acesso à Bucket no Cloud Storage
serviceAccount = '/content/chave_bucket_JSON.json' 
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount

#indicar a bucket
client = storage.Client()
bucket = client.get_bucket('bc26-datasets-comex')
# bucket = client.get_bucket('comex-original-link')

In [ ]:
# # Para acessar o arquivo que está na bucket
# bucket.blob('bc26-datasets-comex/EXP_COMPLETA (NCM).csv')
# #para enviar
# blob = bucket.blob('preco-combustiveis-2013-2022')
# blob.upload_from_filename('/content/preco-combustiveis-2013-2022')

#Upload dos arquivos no Bucket do Cloud Storage

In [ ]:
#link das bases usadas da página do ministério da economia
exp_prod = 'https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/EXP_COMPLETA.zip'
imp_prod = 'https://balanca.economia.gov.br/balanca/bd/comexstat-bd/ncm/IMP_COMPLETA.zip'
exp_munc = 'https://balanca.economia.gov.br/balanca/bd/comexstat-bd/mun/EXP_COMPLETA_MUN.zip'
imp_munc = 'https://balanca.economia.gov.br/balanca/bd/comexstat-bd/mun/IMP_COMPLETA_MUN.zip'
#elas foram descompactadas, seu formato era csv, elas foram mudadas para parquet para um melhor desempenho e 
#enviadas para o bucket como orginial contendo os 10 anos de interrese.

#link da tabelas auxiliares, usadas para a tradução dos códigos.
cod_aux = 'https://balanca.economia.gov.br/balanca/bd/tabelas/TABELAS_AUXILIARES.xlsx'

NCM (Nomenclatura Comum do Mercosul) é um código de oito dígitos estabelecido pela legislação federal para identificar as mercadorias e facilitar o comércio internacional, obrigatoriamente na NF-e, NFA-e e NFC-e.

In [ ]:
#relação do código ncm com os outro códigos de classificação de protudos, junto com sua descrioção
ncm = 'https://balanca.economia.gov.br/balanca/bd/tabelas/NCM.csv'

#retirar o conteudo do link
request_text = requests.get(ncm).content
#enviar o conteudo para o bucket, indicando o formato
bucket.blob('ncm').upload_from_string(request_text, 'text/csv')


base de serie historia mensais de preço de combustível

In [ ]:
# link da página da agencia nacional do petroleo, gas natural  e biocombustiveis
#séries históricas mensais
comb15 = 'https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/shlp/mensal/mensal-municipios-2013-a-2015.xlsx'
comb18 = 'https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/shlp/mensal/mensal-municipios-2016-a-2018.xlsx'
comb21 = 'https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/shlp/mensal/mensal-municipios-2019-a-2021.xlsx'
comb22 = 'https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/shlp/mensal/mensal-municipios-desde-jan2022.xlsx'

In [ ]:
#pegar o conteudo do link
request_text = requests.get(comb15).content
#enviar o conteudo para o bucket
bucket.blob('comex-original-link/municipio-2013-2015').upload_from_string(request_text, 'xlsx')

In [ ]:
#pegar o conteudo do link
request_text = requests.get(comb18).content
#enviar o conteudo para o bucket
bucket.blob('comex-original-link/municipio-2016-2018').upload_from_string(request_text, 'xlsx')

In [ ]:
#pegar o conteudo do link
request_text = requests.get(comb21).content
#enviar o conteudo para o bucket
bucket.blob('comex-original-link/municipio-2019-2021').upload_from_string(request_text, 'xlsx')

In [ ]:
#pegar o conteudo do link
request_text = requests.get(comb22).content
#enviar o conteudo para o bucket
bucket.blob('comex-original-link/municipio-apartir-2022').upload_from_string(request_text, 'xlsx')

In [ ]:
pathtest = 'gs://bc26-datasets-comex/comex-original-link/municipio-apartir-2022'
mun22 = pd.read_excel(pathtest, skiprows=16)
#pulas as primeiras 16 linha, pois a base só começa depois

In [ ]:
mun22.tail(20)
#abriu o arquivo correto!

In [ ]:
#link da série semanal em xlsb - a formatação da data a deforma
d = 'https://www.gov.br/anp/pt-br/assuntos/precos-e-defesa-da-concorrencia/precos/precos-revenda-e-de-distribuicao-combustiveis/shlp/semanal/semanal-municipios-2013-a-2017.xlsb'
#pegar o conteudo do link
request_text = requests.get(d).content
#enviar o conteudo para o bucket
bucket.blob('comex-original-link/semana-municipio-2013-2015').upload_from_string(request_text, 'xlsx')

In [ ]:

di = pd.read_excel('', skiprows=16)

#tabela de numeros validados

código para ler sheet do excel

In [ ]:
#ler xlsx com sheet
df = pd.read_excel('file.xlsx', sheet_name=0)

In [ ]:
val = pd.read_csv('https://balanca.economia.gov.br/balanca/bd/repetro/exp_repetro.xlsx')

In [ ]:
exp = pd.read_csv('/content/EXP_TOTAIS_CONFERENCIA.csv', sep=';')
imp = pd.read_csv('/content/IMP_TOTAIS_CONFERENCIA.csv', sep=';')

In [ ]:
val
f_exp = exp.CO_ANO >2012
f_imp = exp.CO_ANO >2012

In [ ]:
df1 = exp.loc[f_exp]
df1

ARQUIVO  CO_ANO      QT_ESTAT    KG_LIQUIDO        VL_FOB  \
16  EXP_2013.csv    2013  580193111059  557952370783  232544255606   
17  EXP_2014.csv    2014  485576625760  576395634212  220923236838   
18  EXP_2015.csv    2015  521472343947  636029338192  186782355063   
19  EXP_2016.csv    2016  526840590057  644891914917  179526129214   
20  EXP_2017.csv    2017  560480100308  691743297215  214988108353   
21  EXP_2018.csv    2018  584234291249  705549984512  231889523399   
22  EXP_2019.csv    2019  526083644677  678108051917  221126807647   
23  EXP_2020.csv    2020  503843862451  697446598673  209180241655   
24  EXP_2021.csv    2021  524626711400  700387165796  280814577460   
25  EXP_2022.csv    2022  489301147355  679812308938  308362261446   

    NUMERO_LINHAS  
16        1074709  
17        1057794  
18        1048388  
19        1092692  
20        1096623  
21        1128981  
22        1393174  
23        1344556  
24        1480295  
25        1367084

In [ ]:
df1.sum()

ARQUIVO          EXP_2013.csvEXP_2014.csvEXP_2015.csvEXP_2016.c...
CO_ANO                                                       20175
QT_ESTAT                                             5302652428263
KG_LIQUIDO                                           6568316665155
VL_FOB                                               2286137496681
NUMERO_LINHAS                                             12084296
dtype: object

In [ ]:
df2 = imp.loc[f_imp]
df2

ARQUIVO  CO_ANO      QT_ESTAT    KG_LIQUIDO        VL_FOB  \
16  IMP_2013.csv    2013  237939643436  159565878109  241500886459   
17  IMP_2014.csv    2014  244079554147  165284900159  230823018796   
18  IMP_2015.csv    2015  207578980463  146470902082  173104259077   
19  IMP_2016.csv    2016  197580870135  138412341184  139321357653   
20  IMP_2017.csv    2017  224138358488  147377404392  158951444003   
21  IMP_2018.csv    2018  242600455025  151392468267  185321983502   
22  IMP_2019.csv    2019  238234076545  153404722395  185927967580   
23  IMP_2020.csv    2020  232969373637  143979868044  158786824879   
24  IMP_2021.csv    2021  276494571488  178410726540  219408049180   
25  IMP_2022.csv    2022  236358982722  158139876395  250831426836   

       VL_FRETE  VL_SEGURO  NUMERO_LINHAS  
16  10585684919  195133145        1887697  
17   9761601940  178751246        1891607  
18   7217609201  138467852        1784459  
19   5814053785  112463368        1690065  
20   6780582952  123205174        1840472  
21   7382864017  135366561        1893229  
22   7099935633  134100825        1932755  
23   7433078641  116311933        1784057  
24  15125230521  157165534        1999946  
25  17964935586  197726287        1856515

In [ ]:
df2.sum()

ARQUIVO          IMP_2013.csvIMP_2014.csvIMP_2015.csvIMP_2016.c...
CO_ANO                                                       20175
QT_ESTAT                                             2337974866086
KG_LIQUIDO                                           1542439087567
VL_FOB                                               1943977217965
VL_FRETE                                               95165577195
VL_SEGURO                                               1488691925
NUMERO_LINHAS                                             18560802
dtype: object

#Carregar base original do bucket para pré-analise

In [ ]:
# DOWNLOAD ARQUIVO DO BUCKET - MARCOS

# FAZER O ACESSO A BUCKET
serviceAccount = '/content/chave_bucket_JSON.json' # Chave de acesso à Bucket no Cloud Storage
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = serviceAccount
client = storage.Client()             

# CRIAR UMA VARIÁVEL PARA RECEBER O NOME DA BUCKET 
bucket = client.get_bucket('bc26-datasets-comex')

# Para acessar o arquivo que está na bucket
bucket.blob('bc26-datasets-comex/EXP_COMPLETA (NCM).csv')

# CRIAR UMA VARIÁVEL PARA RECEBER O CAMINHO DO ARQUIVO
path = 'gs://bc26-datasets-comex/EXP_COMPLETA (NCM).csv'

In [ ]:
#ler a base origal do storage
df = pd.read_csv(path,sep=';')

In [ ]:
df

In [ ]:
#intalação para formato diferente
pip install pyxlsb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
path2 = 'gs://bc26-datasets-comex/semanal-municipios-2013-a-2017.xlsb'
gas = pd.read_excel(path2, skiprows=14)

In [ ]:
gas

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0              41273       41279  CENTRO OESTE    DISTRITO FEDERAL   
1              41273       41279  CENTRO OESTE               GOIAS   
2              41273       41279  CENTRO OESTE               GOIAS   
3              41273       41279  CENTRO OESTE               GOIAS   
4              41273       41279  CENTRO OESTE               GOIAS   
...              ...         ...           ...                 ...   
657867         43093       43099       SUDESTE           SAO PAULO   
657868         43093       43099  CENTRO OESTE  MATO GROSSO DO SUL   
657869         43093       43099       SUDESTE      RIO DE JANEIRO   
657870         43093       43099       SUDESTE      ESPIRITO SANTO   
657871         43093       43099       SUDESTE      RIO DE JANEIRO   

                    MUNICÍPIO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0                    BRASILIA  ETANOL HIDRATADO                            80   
1       AGUAS LINDAS DE GOIAS  ETANOL HIDRATADO                             5   
2                    ANAPOLIS  ETANOL HIDRATADO                            16   
3        APARECIDA DE GOIANIA  ETANOL HIDRATADO                            13   
4                CALDAS NOVAS  ETANOL HIDRATADO                            12   
...                       ...               ...                           ...   
657867        TABOAO DA SERRA               GNV                             1   
657868            TRES LAGOAS               GNV                             1   
657869              TRES RIOS               GNV                             3   
657870                VITORIA               GNV                             1   
657871          VOLTA REDONDA               GNV                             3   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  \
0                   R$/l                2.273               0.022864   
1                   R$/l                2.134               0.043359   
2                   R$/l                1.865               0.054575   
3                   R$/l                1.771               0.022532   
4                   R$/l                1.918               0.105396   
...                  ...                  ...                    ...   
657867             R$/m3                2.290               0.000000   
657868             R$/m3                2.399               0.000000   
657869             R$/m3                2.999               0.000000   
657870             R$/m3                2.399               0.000000   
657871             R$/m3                2.876               0.005774   

        PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  \
0                      2.190                 2.299                0.405   
1                      2.090                 2.190                0.268   
2                      1.690                 1.899                 0.36   
3                      1.730                 1.790                0.206   
4                      1.650                 1.999                0.376   
...                      ...                   ...                  ...   
657867                 2.290                 2.290                    -   
657868                 2.399                 2.399                    -   
657869                 2.999                 2.999                1.061   
657870                 2.399                 2.399                    -   
657871                 2.869                 2.879                    -   

        COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                          0.010                    1.868   
1                          0.020                    1.866   
2                          0.029                    1.505   
3                          0.013                    1.565   
4                          0.055                    1.542   
...                          ...                      ...   
6

In [ ]:
gas.dtypes

DATA INICIAL                       int64
DATA FINAL                         int64
REGIÃO                            object
ESTADO                            object
MUNICÍPIO                         object
PRODUTO                           object
NÚMERO DE POSTOS PESQUISADOS       int64
UNIDADE DE MEDIDA                 object
PREÇO MÉDIO REVENDA              float64
DESVIO PADRÃO REVENDA            float64
PREÇO MÍNIMO REVENDA             float64
PREÇO MÁXIMO REVENDA             float64
MARGEM MÉDIA REVENDA              object
COEF DE VARIAÇÃO REVENDA         float64
PREÇO MÉDIO DISTRIBUIÇÃO          object
DESVIO PADRÃO DISTRIBUIÇÃO        object
PREÇO MÍNIMO DISTRIBUIÇÃO         object
PREÇO MÁXIMO DISTRIBUIÇÃO         object
COEF DE VARIAÇÃO DISTRIBUIÇÃO     object
dtype: object

In [ ]:
#Renomeando colunas
df2.rename(columns={'CO_ANO':'ano',
                   'CO_MES':'mes',
                   'CO_NCM':'codigo_mercadoria',
                   'CO_UNID':'codigo_medida',
                    'CO_PAIS':'pais',
                    'SG_UF_NCM':'estado',
                    'CO_VIA':'cod_meio_transporte',
                    'CO_URF':'cod_aduaneiro',
                    'QT_ESTAT':'qnt_estatistica',
                    'KG_LIQUIDO':'peso_liquido',
                    'VL_FOB':'preco'
                    },inplace=True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(


In [ ]:
f_mes = df.CO_MES == 1
f_ano = df.CO_ANO == 2020
dfjan20 = df.loc[f_mes & f_ano]

In [ ]:
dfjan20
d_est = dfjan20.CO_UNID == 10

In [ ]:
dfjan = dfjan20.loc[d_est]

In [ ]:
dfjan

CO_ANO  CO_MES    CO_NCM  CO_UNID  CO_PAIS SG_UF_NCM  CO_VIA  \
21557974    2020       1  39211900       10      244        SP       4   
21557998    2020       1  20082090       10      850        GO       1   
21558016    2020       1  31052000       10      586        PR       7   
21558018    2020       1  84139190       10      845        SP       7   
21558029    2020       1   7032010       10      628        RJ       1   
...          ...     ...       ...      ...      ...       ...     ...   
22902462    2020       1  19021900       10      337        AM       0   
22902494    2020       1   7108000       10      137        PR       1   
22902505    2020       1  85030090       10      676        SC       1   
22902507    2020       1   8039000       10      267        SP      12   
22902515    2020       1  48201000       10      476        SP       1   

           CO_URF  QT_ESTAT  KG_LIQUIDO  VL_FOB  
21557974   817600         1           1       2  
21557998   817800      1440        1440    4158  
21558016   147700   2347000     2347000  775700  
21558018  1017701       437         437   34669  
21558029   717600        10          10      40  
...           ...       ...         ...     ...  
22902462   260152        40          40      72  
22902494   917800         5           5      10  
22902505   927700        12          12      24  
22902507   817800        35          35      26  
22902515   717600        10           1      17  

[67645 rows x 11 columns]

In [ ]:
dfjan.CO_NCM.is_unique
dfjan.SG_UF_NCM.is_unique
f7032010 = dfjan.CO_NCM == 7032010

In [ ]:
df7032010 =dfjan.loc[f7032010]
df7032010

CO_ANO  CO_MES   CO_NCM  CO_UNID  CO_PAIS SG_UF_NCM  CO_VIA  \
21558029    2020       1  7032010       10      628        RJ       1   
21622159    2020       1  7032010       10      580        RS       1   
21748896    2020       1  7032010       10      434        RS       1   
21838181    2020       1  7032010       10       23        RJ       1   
21884434    2020       1  7032010       10      538        RS       1   
21921986    2020       1  7032010       10      351        PR       1   
21925272    2020       1  7032010       10       83        RS       1   
21948369    2020       1  7032010       10      741        RS       1   
22203190    2020       1  7032010       10      476        RS       1   
22294967    2020       1  7032010       10      361        RJ       1   
22473088    2020       1  7032010       10      361        RJ       1   
22547272    2020       1  7032010       10      160        RS       1   
22571496    2020       1  7032010       10      301        PA       1   
22576460    2020       1  7032010       10      301        RJ       1   
22598939    2020       1  7032010       10      573        RS       1   
22637308    2020       1  7032010       10      361        RJ       1   
22678063    2020       1  7032010       10      580        PR       1   
22731954    2020       1  7032010       10       23        RJ       1   
22740515    2020       1  7032010       10      351        RS       1   
22779457    2020       1  7032010       10      573        SC      14   

           CO_URF  QT_ESTAT  KG_LIQUIDO  VL_FOB  
21558029   717600        10          10      40  
21622159  1017700        10          10      55  
21748896  1017700        21          21     166  
21838181   717600         5           5       7  
21884434  1017700        15          15     108  
21921986   917800        25          25      85  
21925272  1017700        10          10      60  
21948369  1017700         7           7      56  
22203190  1017700        38          38     264  
22294967   717800        10          10      42  
22473088   717600        25          25      52  
22547272  1017700        15          15      97  
22571496   217800        13          13      43  
22576460   717800        60          60     274  
22598939  1017700         2           2      16  
22637308   710251        20          20      98  
22678063   917800        28          28      93  
22731954   717800        93          93     279  
22740515  1017700        25          25     149  
22779457   917800         1           1       3

spark

In [ ]:
dfsjan20 = spark.createDataFrame(dfjan20)

In [ ]:
dfsjan20.show()

#tabelas auxiliares xlsx com sheets

##pegando todos os sheet das tabelas auxiliares

In [ ]:
#abrir todas as sheet
# Para acessar o arquivo que está na bucket
bucket.blob('bc26-datasets-comex/TABELAS_AUXILIARES.xlsx')

# CRIAR UMA VARIÁVEL PARA RECEBER O CAMINHO DO ARQUIVO
path = 'gs://bc26-datasets-comex/TABELAS_AUXILIARES.xlsx'

In [ ]:
#laço de repetição para adicionar posições na lista.
cod = []
for i in range(16):
  cod.append(str('df')+str(i))
  print(cod[i])

df0
df1
df2
df3
df4
df5
df6
df7
df8
df9
df10
df11
df12
df13
df14
df15


SH - sistema harminizado
CUCI - Classificação Uniforme para Comercio Internacional
CGCE - Classificação por Grandes Categorias Econômicas
ISIC - International Standard Industruial Classification
SIIT - Setores Industriais por Intensidade Tecnológica
PPE - Pauta de Protudos Exportados (categoria da SECEX)
PPI - Pauta de Portudos Importados (categoria da SECEX)

In [ ]:
cod = []

#abrir a sheets
for i in range(16):
  cod.append('i')
  cod[i] = pd.read_excel(path, sheet_name=(i+1))
#Carregar as 16 sheet da tabel auxiliar

##analisando os sheet

In [ ]:
#relação entre NCM e SH
cod[0]
#tem nomes em portugues, espenhol e ingles do SH4 e SH6
#o SH6 é o NCM sem os 2 últimos dígitos
#o SH$ é o NCM sem os 4 últimos dígitos
#o SH$ é o NCM sem os 6 últimos dígitos
#o sec é categoria

CO_NCM                                         NO_NCM_POR  CO_SH6  \
0       1011010                  Cavalos reprodutores de raça pura   10110   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   10110   
2       1011100                 Cavalos reprodutores, de raça pura   10111   
3       1011900                              Outros cavalos, vivos   10119   
4       1012000                            Asininos e muares vivos   10120   
...         ...                                                ...     ...   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM  999971   
13594  99997104               Outros artigos do capitulo 71 da NCM  999971   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial  999999   
13596  99999951      Devolução antes da DI (exportação definitiva)  999999   
13597  99999960                                       Reexportação  999999   

                                              NO_SH6_POR  \
0      Animais vivos das espécies cavalar, asinina e ...   
1      Animais vivos das espécies cavalar, asinina e ...   
2                     Cavalos reprodutores, de raça pura   
3                                  Outros cavalos, vivos   
4                                Asininos e muares vivos   
...                                                  ...   
13593    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13594    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13595  Qualquer outra mercadoria sem cobertura cambia...   
13596  Qualquer outra mercadoria sem cobertura cambia...   
13597  Qualquer outra mercadoria sem cobertura cambia...   

                                              NO_SH6_ESP  \
0           Caballos y asnos, reproductores de raza pura   
1           Caballos y asnos, reproductores de raza pura   
2                    Caballos reproductores de raza pura   
3                                  Demás caballos, vivos   
4                       Asnos, mulos y burdéganos, vivos   
...                                                  ...   
13593            Piedras, en bruto o no, del capítulo 71   
13594            Piedras, en bruto o no, del capítulo 71   
13595  Todos otros bienes  sin cobertura de cambios y...   
13596  Todos otros bienes  sin cobertura de cambios y...   
13597  Todos otros bienes  sin cobertura de cambios y...   

                                             NO_SH6_ING  CO_SH4  \
0                   Pure-bred breeding horses and asses     101   
1                   Pure-bred breeding horses and asses     101   
2                             Pure-bred breeding horses     101   
3                                     Other live horses     101   
4                       Asses, mules and hinnies (live)     101   
...                                                 ...     ...   
13593            Stones, raw or worked, from Chapter 71    9999   
13594            Stones, raw or worked, from Chapter 71    9999   
13595  Any other goods without exchange cover; reexport    9999   
13596  Any other goods without exchange cover; reexport    9999   
13597  Any other goods without exchange cover; reexport    9999   

                                              NO_SH4_POR  \
0                      Cavalos, asininos e muares, vivos   
1                      Cavalos, asininos e muares, vivos   
2                      Cavalos, asininos e muares, vivos   
3                      Cavalos, asininos e muares, vivos   
4                      Cavalos, asininos e muares, vivos   
...                                                  ...   
13593  Consumo de bordo (exceto combustíveis e lubrif...   
13594  Consumo de bordo (exceto combustíveis e lubrif...   
13595  Consumo de bordo (exceto combustíveis e lubrif...   
13596  Consumo de bordo (exceto combustíveis e lubrif...   
13597  Consumo de bordo (exceto combustíveis e lubrif...   

                                              NO_SH4_ESP  \
0             Caballos, asnos, mulos y burdé

In [ ]:
#Relação NCM com CUCI, Grupo/divisão CUCI e segmento
cod[1]

CO_NCM                                         NO_NCM_POR  \
0       1011010                  Cavalos reprodutores de raça pura   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   
2       1011100                 Cavalos reprodutores, de raça pura   
3       1011900                              Outros cavalos, vivos   
4       1012000                            Asininos e muares vivos   
...         ...                                                ...   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM   
13594  99997104               Outros artigos do capitulo 71 da NCM   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial   
13596  99999951      Devolução antes da DI (exportação definitiva)   
13597  99999960                                       Reexportação   

      CO_CUCI_ITEM                                       NO_CUCI_ITEM  \
0             0015               Cavalos, asnos, mulas e burros vivos   
1             0015               Cavalos, asnos, mulas e burros vivos   
2             0015               Cavalos, asnos, mulas e burros vivos   
3             0015               Cavalos, asnos, mulas e burros vivos   
4             0015               Cavalos, asnos, mulas e burros vivos   
...            ...                                                ...   
13593         9310  Operações especiais e commodities não classifi...   
13594         9310  Operações especiais e commodities não classifi...   
13595         9310  Operações especiais e commodities não classifi...   
13596         9310  Operações especiais e commodities não classifi...   
13597         9310  Operações especiais e commodities não classifi...   

       CO_CUCI_SUB                                        NO_CUCI_SUB  \
0               15               Cavalos, asnos, mulas e burros vivos   
1               15               Cavalos, asnos, mulas e burros vivos   
2               15               Cavalos, asnos, mulas e burros vivos   
3               15               Cavalos, asnos, mulas e burros vivos   
4               15               Cavalos, asnos, mulas e burros vivos   
...            ...                                                ...   
13593         9310  Operações especiais e commodities não classifi...   
13594         9310  Operações especiais e commodities não classifi...   
13595         9310  Operações especiais e commodities não classifi...   
13596         9310  Operações especiais e commodities não classifi...   
13597         9310  Operações especiais e commodities não classifi...   

      CO_CUCI_GRUPO                                      NO_CUCI_GRUPO  \
0               001  Animais vivos, não incluído pescados ou crustá...   
1               001  Animais vivos, não incluído pescados ou crustá...   
2               001  Animais vivos, não incluído pescados ou crustá...   
3               001  Animais vivos, não incluído pescados ou crustá...   
4               001  Animais vivos, não incluído pescados ou crustá...   
...             ...                                                ...   
13593           931  Operações especiais e commodities não classifi...   
13594           931  Operações especiais e commodities não classifi...   
13595           931  Operações especiais e commodities não classifi...   
13596           931  Operações especiais e commodities não classifi...   
13597           931  Operações especiais e commodities não classifi...   

       CO_CUCI_DIVISAO                                    NO_CUCI_DIVISAO  \
0                    0         Animais vivos não incluídos no capítulo 03   
1                    0         Animais vivos não incluídos no capítulo 03   
2                    0         Animais vivos não incluídos no capítulo 03   
3                    0         Animais vivos não incluídos no capítulo 03   
4                    0         Animais vivos não incluídos no capítulo 03   
...                ...                                         

In [ ]:
#relação NCM com CGCE n3/n2 e n1 (tipo de bens)
cod[2]

CO_NCM                                         NO_NCM_POR  \
0       1011010                  Cavalos reprodutores de raça pura   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   
2       1011100                 Cavalos reprodutores, de raça pura   
3       1011900                              Outros cavalos, vivos   
4       1012000                            Asininos e muares vivos   
...         ...                                                ...   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM   
13594  99997104               Outros artigos do capitulo 71 da NCM   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial   
13596  99999951      Devolução antes da DI (exportação definitiva)   
13597  99999960                                       Reexportação   

       CO_CGCE_N3                                         NO_CGCE_N3  \
0             110  Bens de capital (exceto equipamentos de transp...   
1             110  Bens de capital (exceto equipamentos de transp...   
2             110  Bens de capital (exceto equipamentos de transp...   
3             210  Alimentos e bebidas básicos, destinados princi...   
4             110  Bens de capital (exceto equipamentos de transp...   
...           ...                                                ...   
13593         311  Bens de consumo duráveis – exceto equipamentos...   
13594         322                       Bens de consumo não duráveis   
13595         999               Bens não especificados anteriormente   
13596         999               Bens não especificados anteriormente   
13597         999               Bens não especificados anteriormente   

                                          NO_CGCE_N3_ING  \
0      Capital goods, except industrial transport equ...   
1      Capital goods, except industrial transport equ...   
2      Capital goods, except industrial transport equ...   
3          Basic food and beverages, mainly for industry   
4      Capital goods, except industrial transport equ...   
...                                                  ...   
13593  Durable consumer goods - except transport equi...   
13594                                  Non-durable goods   
13595                      Goods not otherwise specified   
13596                      Goods not otherwise specified   
13597                      Goods not otherwise specified   

                                          NO_CGCE_N3_ESP  CO_CGCE_N2  \
0      Bienes de capital, excepto equipo de transport...          11   
1      Bienes de capital, excepto equipo de transport...          11   
2      Bienes de capital, excepto equipo de transport...          11   
3      Alimentos y bebidas básicos, principalmente pa...          21   
4      Bienes de capital, excepto equipo de transport...          11   
...                                                  ...         ...   
13593  Bienes de consumo durables - excepto equipo de...          31   
13594                      Bienes de consumo no durables          32   
13595          Bienes no especificados en otra categoría          99   
13596          Bienes no especificados en otra categoría          99   
13597          Bienes no especificados en otra categoría          99   

                                              NO_CGCE_N2  \
0      Bens de capital, exceto equipamentos de transp...   
1      Bens de capital, exceto equipamentos de transp...   
2      Bens de capital, exceto equipamentos de transp...   
3      Alimentos e bebidas básicos, destinados princi...   
4      Bens de capital, exceto equipamentos de transp...   
...                                                  ...   
13593                           Bens de consumo duráveis   
13594        Bens de consumo semiduráveis e não duráveis   
13595               Bens não especificados anteriormente   
13596               Bens não especificados anteriormente   
13597               Bens não especificados anteriormente 

In [ ]:
#relação NCM com ISIC classe, grupo, divisão, seção (aréa de atuação)
cod[3]

CO_NCM                                         NO_NCM_POR  \
0       1011010                  Cavalos reprodutores de raça pura   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   
2       1011100                 Cavalos reprodutores, de raça pura   
3       1011900                              Outros cavalos, vivos   
4       1012000                            Asininos e muares vivos   
...         ...                                                ...   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM   
13594  99997104               Outros artigos do capitulo 71 da NCM   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial   
13596  99999951      Devolução antes da DI (exportação definitiva)   
13597  99999960                                       Reexportação   

       CO_ISIC_CLASSE                       NO_ISIC_CLASSE  \
0                 142  Criação de cavalos e outros equinos   
1                 142  Criação de cavalos e outros equinos   
2                 142  Criação de cavalos e outros equinos   
3                 142  Criação de cavalos e outros equinos   
4                 142  Criação de cavalos e outros equinos   
...               ...                                  ...   
13593            8999                     Não classificado   
13594            8999                     Não classificado   
13595            8999                     Não classificado   
13596            8999                     Não classificado   
13597            8999                     Não classificado   

                        NO_ISIC_CLASSE_ING  \
0      Raising of horses and other equines   
1      Raising of horses and other equines   
2      Raising of horses and other equines   
3      Raising of horses and other equines   
4      Raising of horses and other equines   
...                                    ...   
13593                       Not Classified   
13594                       Not Classified   
13595                       Not Classified   
13596                       Not Classified   
13597                       Not Classified   

                        NO_ISIC_CLASSE_ESP  CO_ISIC_GRUPO     NO_ISIC_GRUPO  \
0      Criação de cavalos e outros equinos             14   Produção animal   
1      Criação de cavalos e outros equinos             14   Produção animal   
2      Criação de cavalos e outros equinos             14   Produção animal   
3      Criação de cavalos e outros equinos             14   Produção animal   
4      Criação de cavalos e outros equinos             14   Produção animal   
...                                    ...            ...               ...   
13593                     Não classificado            899  Não classificado   
13594                     Não classificado            899  Não classificado   
13595                     Não classificado            899  Não classificado   
13596                     Não classificado            899  Não classificado   
13597                     Não classificado            899  Não classificado   

       NO_ISIC_GRUPO_ING NO_ISIC_GRUPO_ESP  CO_ISIC_DIVISAO  \
0      Animal production   Produção animal                1   
1      Animal production   Produção animal                1   
2      Animal production   Produção animal                1   
3      Animal production   Produção animal                1   
4      Animal production   Produção animal                1   
...                  ...               ...              ...   
13593     Not Classified  Não classificado               89   
13594     Not Classified  Não classificado               89   
13595     Not Classified  Não classificado               89   
13596     Not Classified  Não classificado               89   
13597     Not Classified  Não classificado               89   

                       NO_ISIC_DIVISAO  \
0      Produção vegetal, animal e caça   
1      Produção vegetal, animal e caça   
2      Produção vegetal, animal e caça

In [ ]:
#relação NCM o com o ISIC seção e grupo
cod[15]

CO_NCM                                         NO_NCM_POR  \
0       1011010                  Cavalos reprodutores de raça pura   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   
2       1011100                 Cavalos reprodutores, de raça pura   
3       1011900                              Outros cavalos, vivos   
4       1012000                            Asininos e muares vivos   
...         ...                                                ...   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM   
13594  99997104               Outros artigos do capitulo 71 da NCM   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial   
13596  99999951      Devolução antes da DI (exportação definitiva)   
13597  99999960                                       Reexportação   

      CO_ISIC_SECAO    NO_ISIC_SECAO CO_CUCI_GRUPO  \
0                 A     Agropecuária           001   
1                 A     Agropecuária           001   
2                 A     Agropecuária           001   
3                 A     Agropecuária           001   
4                 A     Agropecuária           001   
...             ...              ...           ...   
13593             D  Outros Produtos           931   
13594             D  Outros Produtos           931   
13595             D  Outros Produtos           931   
13596             D  Outros Produtos           931   
13597             D  Outros Produtos           931   

                                           NO_CUCI_GRUPO  
0      Animais vivos, não incluído pescados ou crustá...  
1      Animais vivos, não incluído pescados ou crustá...  
2      Animais vivos, não incluído pescados ou crustá...  
3      Animais vivos, não incluído pescados ou crustá...  
4      Animais vivos, não incluído pescados ou crustá...  
...                                                  ...  
13593  Operações especiais e commodities não classifi...  
13594  Operações especiais e commodities não classifi...  
13595  Operações especiais e commodities não classifi...  
13596  Operações especiais e commodities não classifi...  
13597  Operações especiais e commodities não classifi...  

[13598 rows x 6 columns]

In [ ]:
#relaciona o NCM com o SIIT
cod[4]
#4 categorias de SIIT pelo uso de tecnologia na industria (Premissa: produtos com valor de agregação alto ou baixo)
pd.unique(cod[4].CO_SIIT)
pd.unique(cod[4].NO_SIIT)

array(['PRODUTOS N.C.I.T',
       'PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE BAIXA TECNOLOGIA',
       'PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDIA-ALTA TECNOLOGIA',
       'PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDIA-BAIXA TECNOLOGIA',
       'PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE ALTA TECNOLOGIA'],
      dtype=object)

In [ ]:
cod[5].tail(30)
#indica qual a unidade de medida usada com esse NCM

CO_NCM                                         NO_NCM_POR  CO_UNID  \
13568  97031000  Produções originais de arte estatuária ou de e...       11   
13569  97039000  Outras produções originais de arte estatuária ...       11   
13570  97040000  Selos postais, selos fiscais, marcas postais, ...       10   
13571  97050000  Coleções e espécimes para coleções, de zoologi...       10   
13572  97051000  Coleções e peças de coleção que apresentem um ...       10   
13573  97052100                    Espécimes humanos e suas partes       10   
13574  97052900  Outras coleções e peças de coleção que apresen...       10   
13575  97053900   Outras coleções e peças de coleção que aprese...       10   
13576  97060000                  Antiguidades com mais de 100 anos       10   
13577  97061000                  Antiguidades com mais de 250 anos       10   
13578  97069000  Outras Antiguidades com mais de 100 anos, não ...       10   
13579  99900000                          Zonas francas (free-shop)       10   
13580  99910000                                 Encomendas postais       10   
13581  99920000                                           Amostras       10   
13582  99930000  Comércio de combustíveis de panol, apetrechos,...       10   
13583  99940000                           Mercadorias em devolução       10   
13584  99950000         Mercadorias em arrendamento não financeiro       10   
13585  99960000                 Bagagem (provenientes de mudanças)       10   
13586  99970000                                 Mercadorias doadas       10   
13587  99980101  Consumo de bordo - combustíveis e lubrificante...       10   
13588  99980102  Consumo de bordo - combustíveis e lubrificante...       10   
13589  99980201  Consumo de bordo - qualquer outra mercadoria p...       10   
13590  99980202  Consumo de bordo - qualquer outra mercadoria p...       10   
13591  99997101              Pedras em bruto do capítulo 71 da NCM       10   
13592  99997102  Pedras lapidadas/trabalhadas do capítulo 71 da...       10   
13593  99997103            Joalheria de ouro do capitulo 71 da NCM       10   
13594  99997104               Outros artigos do capitulo 71 da NCM       10   
13595  99999900    Qualquer outra mercadoria sem cobertura cambial       10   
13596  99999951      Devolução antes da DI (exportação definitiva)       10   
13597  99999960                                       Reexportação       10   

                  NO_UNID SG_UNID  
13568    NUMERO (UNIDADE)   UNID.  
13569    NUMERO (UNIDADE)   UNID.  
13570  QUILOGRAMA LIQUIDO   KGL    
13571  QUILOGRAMA LIQUIDO   KGL    
13572  QUILOGRAMA LIQUIDO   KGL    
13573  QUILOGRAMA LIQUIDO   KGL    
13574  QUILOGRAMA LIQUIDO   KGL    
13575  QUILOGRAMA LIQUIDO   KGL    
13576  QUILOGRAMA LIQUIDO   KGL    
13577  QUILOGRAMA LIQUIDO   KGL    
13578  QUILOGRAMA LIQUIDO   KGL    
13579  QUILOGRAMA LIQUIDO   KGL    
13580  QUILOGRAMA LIQUIDO   KGL    
13581  QUILOGRAMA LIQUIDO   KGL    
13582  QUILOGRAMA LIQUIDO   KGL    
13583  QUILOGRAMA LIQUIDO   KGL    
13584  QUILOGRAMA LIQUIDO   KGL    
13585  QUILOGRAMA LIQUIDO   KGL    
13586  QUILOGRAMA LIQUIDO   KGL    
13587  QUILOGRAMA LIQUIDO   KGL    
13588  QUILOGRAMA LIQUIDO   KGL    
13589  QUILOGRAMA LIQUIDO   KGL    
13590  QUILOGRAMA LIQUIDO   KGL    
13591  QUILOGRAMA LIQUIDO   KGL    
13592  QUILOGRAMA LIQUIDO   KGL    
13593  QUILOGRAMA LIQUIDO   KGL    
13594  QUILOGRAMA LIQUIDO   KGL    
13595  QUILOGRAMA LIQUIDO   KGL    
13596  QUILOGRAMA LIQUIDO   KGL    
13597  QUILOGRAMA LIQUIDO   KGL

In [ ]:
cod[6]
#NCM com fator de agregação
pd.unique(cod[6].NO_FAT_AGREG)
#tem 6 categorias
pd.unique(cod[6].NO_FAT_AGREG_GP)
#tem 3 categorias

array(['PRODUTOS BASICOS', 'PRODUTOS INDUSTRIALIZADOS',
       'OPERACOES ESPECIAIS'], dtype=object)

In [ ]:
cod[7]
#o PPI atribuido ao NCM, código de produto
pd.unique(cod[7].NO_PPI)
cod[8]
#o PPE de cada NCM 

CO_NCM                                         NO_NCM_POR  CO_PPE  \
0       1011010                  Cavalos reprodutores de raça pura    1990   
1       1011090  Animais da espécie asinina/muar, reprodutores,...    1990   
2       1011100                 Cavalos reprodutores, de raça pura    1990   
3       1011900                              Outros cavalos, vivos    1990   
4       1012000                            Asininos e muares vivos    1990   
...         ...                                                ...     ...   
13317  99997103            Joalheria de ouro do capitulo 71 da NCM    4020   
13318  99997104               Outros artigos do capitulo 71 da NCM    4020   
13319  99999900    Qualquer outra mercadoria sem cobertura cambial    4010   
13320  99999951      Devolução antes da DI (exportação definitiva)    6010   
13321  99999960                                       Reexportação    6010   

                                                  NO_PPE  \
0                                DEMAIS PRODUTOS BASICOS   
1                                DEMAIS PRODUTOS BASICOS   
2                                DEMAIS PRODUTOS BASICOS   
3                                DEMAIS PRODUTOS BASICOS   
4                                DEMAIS PRODUTOS BASICOS   
...                                                  ...   
13317  TRANSACOES ESPECIAIS - PEDRAS EM BRUTO DO CAP....   
13318  TRANSACOES ESPECIAIS - PEDRAS EM BRUTO DO CAP....   
13319                      TRANSACOES ESPECIAIS - DEMAIS   
13320                                       REEXPORTACAO   
13321                                       REEXPORTACAO   

                                              NO_PPE_MIN  \
0                                Demais produtos básicos   
1                                Demais produtos básicos   
2                                Demais produtos básicos   
3                                Demais produtos básicos   
4                                Demais produtos básicos   
...                                                  ...   
13317  Transações especiais - pedras em bruto do cap....   
13318  Transações especiais - pedras em bruto do cap....   
13319                      Transações especiais - demais   
13320                                       Reexportação   
13321                                       Reexportação   

                                              NO_PPE_ING  
0                                      OTHER BASIC GOODS  
1                                      OTHER BASIC GOODS  
2                                      OTHER BASIC GOODS  
3                                      OTHER BASIC GOODS  
4                                      OTHER BASIC GOODS  
...                                                  ...  
13317  SPECIAL TRANSACTIONS - CRUDE STONES OF CAP.71 ...  
13318  SPECIAL TRANSACTIONS - CRUDE STONES OF CAP.71 ...  
13319                       SPECIAL TRANSACTIONS - OTHER  
13320                                           REEXPORT  
13321                                           REEXPORT  

[13322 rows x 6 columns]

In [ ]:
cod[9]
#nome e sigla dos países para CO_pais
cod[10]
#indica o bloco do pais, pelo CO_Pais

CO_PAIS  CO_BLOCO             NO_BLOCO                NO_BLOCO_ING  \
0        788        51               África  Africa (minus MIDDLE EAST)   
1        525        51               África  Africa (minus MIDDLE EAST)   
2        229        51               África  Africa (minus MIDDLE EAST)   
3        281        51               África  Africa (minus MIDDLE EAST)   
4        438        51               África  Africa (minus MIDDLE EAST)   
..       ...       ...                  ...                         ...   
317       15        22  União Europeia - UE         European Union (EU)   
318       23        22  União Europeia - UE         European Union (EU)   
319      393        22  União Europeia - UE         European Union (EU)   
320      791        22  União Europeia - UE         European Union (EU)   
321      573        22  União Europeia - UE         European Union (EU)   

                     NO_BLOCO_ESP  
0    África (menos ORIENTE MEDIO)  
1    África (menos ORIENTE MEDIO)  
2    África (menos ORIENTE MEDIO)  
3    África (menos ORIENTE MEDIO)  
4    África (menos ORIENTE MEDIO)  
..                            ...  
317            Uniao Europea (UE)  
318            Uniao Europea (UE)  
319            Uniao Europea (UE)  
320            Uniao Europea (UE)  
321            Uniao Europea (UE)  

[322 rows x 5 columns]

In [ ]:
cod[11]
#pela CO-UF diz a sigla, nome do estado e país
cod[12]
# pelo CO-MUN_GEO indica nome do município e estado

CO_MUN_GEO                    NO_MUN                NO_MUN_MIN SG_UF
0        1501758  BREJO GRANDE DO ARAGUAIA  Brejo Grande do Araguaia    PA
1        1501782               BREU BRANCO               Breu Branco    PA
2        1501808                    BREVES                    Breves    PA
3        1501907                    BUJARU                    Bujaru    PA
4        1501956        CACHOEIRA DO PIRIA        Cachoeira do Piriá    PA
...          ...                       ...                       ...   ...
5565     4322350            UNIAO DA SERRA            União da Serra    RS
5566     4322376                 UNISTALDA                 Unistalda    RS
5567     4322400                URUGUAIANA                Uruguaiana    RS
5568     4322509                   VACARIA                   Vacaria    RS
5569     4322525                VALE VERDE                Vale Verde    RS

[5570 rows x 4 columns]

In [ ]:
cod[13]
#pelo CO_VIA diz o meio de transporte
#tem não declareda e desconhecida

CO_VIA                       NO_VIA
0        0            VIA NAO DECLARADA
1        1                     MARITIMA
2        2                      FLUVIAL
3        3                     LACUSTRE
4        4                        AEREA
5        5                       POSTAL
6        6                  FERROVIARIA
7        7                   RODOVIARIA
8        8  CONDUTO/REDE DE TRANSMISSAO
9        9               MEIOS PROPRIOS
10      10          ENTRADA/SAIDA FICTA
11      99             VIA DESCONHECIDA
12      13                  POR REBOQUE
13      11                      COURIER
14      15          VICINAL FRONTEIRICO
15      14                        DUTOS
16      12                      EM MAOS

In [ ]:
cod[14]
#pelo CO-URF indica de onde saiu, contem não informados
pd.unique(cod[14].NO_URF)
pontos_saida = pd.unique(cod[14].NO_URF)
len(pontos_saida)

277

##montar dataframe com as colunas de classificação

In [ ]:
#verirficar se as colunas são únicas para usar como atributo-chave
cod[0].CO_NCM.is_unique
cod[0].shape
cod[0].CO_SH6.is_unique
cod[0].dtypes

CO_NCM            int64
NO_NCM_POR       object
CO_SH6            int64
NO_SH6_POR       object
NO_SH6_ESP       object
NO_SH6_ING       object
CO_SH4            int64
NO_SH4_POR       object
NO_SH4_ESP       object
NO_SH4_ING       object
CO_SH2            int64
NO_SH2_POR       object
NO_SH2_ESP       object
NO_SH2_ING       object
CO_NCM_SECROM    object
NO_SEC_POR       object
NO_SEC_ESP       object
NO_SEC_ING       object
dtype: object

In [ ]:
#entidade chave -NCM cod, NCM descrição - menor nível de classificação

#acrescetar o sh6 correspondente sh6 - codigo, sh2-capitulo, sh4- posição no capitulo.
#colocar o sh6 cod e nome, sh2 e sh 4 só nome
#co_ncm_secron tem 22 valores - é a seção do NCM
#Esses códigos vão do menor envolvimento humano (animais vivos) ao máximo (obras de arte)

In [ ]:
#selecionar as colunas criando um novo dataframe
df_sh = cod[0].loc[:,['CO_NCM','NO_NCM_POR','CO_SH6','NO_SH6_POR','NO_SH4_POR','NO_SH2_POR','NO_SEC_POR']]
df_sh.shape

(13598, 7)

In [ ]:
#verifciar se a coluna é única para usa-la como atributi chave
cod[1].CO_NCM.is_unique
cod[1].shape
cod[1].dtypes

CO_NCM              int64
NO_NCM_POR         object
CO_CUCI_ITEM       object
NO_CUCI_ITEM       object
CO_CUCI_SUB         int64
NO_CUCI_SUB        object
CO_CUCI_GRUPO      object
NO_CUCI_GRUPO      object
CO_CUCI_DIVISAO     int64
NO_CUCI_DIVISAO    object
CO_CUCI_SEC         int64
NO_CUCI_SEC        object
dtype: object

In [ ]:
#classificação internacional intermediária
df_cuci = cod[1].loc[:,['CO_NCM','CO_CUCI_ITEM','NO_CUCI_ITEM','NO_CUCI_SUB','NO_CUCI_GRUPO','NO_CUCI_DIVISAO','NO_CUCI_SEC']]
df_cuci.shape

(13598, 7)

In [ ]:
#verificar novamente
cod[2].CO_NCM.is_unique
cod[2].shape
cod[2].dtypes

CO_NCM             int64
NO_NCM_POR        object
CO_CGCE_N3         int64
NO_CGCE_N3        object
NO_CGCE_N3_ING    object
NO_CGCE_N3_ESP    object
CO_CGCE_N2         int64
NO_CGCE_N2        object
NO_CGCE_N2_ING    object
NO_CGCE_N2_ESP    object
CO_CGCE_N1         int64
NO_CGCE_N1        object
NO_CGCE_N1_ING    object
NO_CGCE_N1_ESP    object
dtype: object

In [ ]:
#class de grandes categorias economicas
df_cgce = cod[2].loc[:,['CO_NCM','CO_CGCE_N3','NO_CGCE_N3','NO_CGCE_N2','NO_CGCE_N1']]
df_cgce.shape

(13598, 5)

In [ ]:
#ver as respostas ditintas da coluna
pd.unique(df_cgce.CO_CGCE_N3)

array([110, 210, 324, 220, 322, 323, 230, 240, 421, 410, 420, 321, 270,
       280, 311, 999, 120, 312, 313])

In [ ]:
cod[3].CO_NCM.is_unique
#ver as informações dessa expecífica tabela auxiliar
cod[3].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13598 entries, 0 to 13597
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   CO_NCM               13598 non-null  int64 
 1   NO_NCM_POR           13598 non-null  object
 2   CO_ISIC_CLASSE       13598 non-null  int64 
 3   NO_ISIC_CLASSE       13598 non-null  object
 4   NO_ISIC_CLASSE_ING   13598 non-null  object
 5   NO_ISIC_CLASSE_ESP   13598 non-null  object
 6   CO_ISIC_GRUPO        13598 non-null  int64 
 7   NO_ISIC_GRUPO        13598 non-null  object
 8   NO_ISIC_GRUPO_ING    13598 non-null  object
 9   NO_ISIC_GRUPO_ESP    13598 non-null  object
 10  CO_ISIC_DIVISAO      13598 non-null  int64 
 11  NO_ISIC_DIVISAO      13598 non-null  object
 12  NO_ISIC_DIVISAO_ING  13598 non-null  object
 13  NO_ISIC_DIVISAO_ESP  13598 non-null  object
 14  CO_ISIC_SECAO        13598 non-null  object
 15  NO_ISIC_SECAO        13598 non-null  object
 16  NO_I

In [ ]:
#isic - class internacional de atividades economias, sustitui o fator agregado, com 4 grandes grupos.
df_isic = cod[3].loc[:,['CO_NCM','CO_ISIC_CLASSE','NO_ISIC_CLASSE','NO_ISIC_GRUPO','NO_ISIC_DIVISAO','NO_ISIC_SECAO']]
df_isic.shape

(13598, 6)

In [ ]:
df_cuci.tail()

CO_NCM CO_CUCI_ITEM  \
13593  99997103         9310   
13594  99997104         9310   
13595  99999900         9310   
13596  99999951         9310   
13597  99999960         9310   

                                            NO_CUCI_ITEM  \
13593  Operações especiais e commodities não classifi...   
13594  Operações especiais e commodities não classifi...   
13595  Operações especiais e commodities não classifi...   
13596  Operações especiais e commodities não classifi...   
13597  Operações especiais e commodities não classifi...   

                                             NO_CUCI_SUB  \
13593  Operações especiais e commodities não classifi...   
13594  Operações especiais e commodities não classifi...   
13595  Operações especiais e commodities não classifi...   
13596  Operações especiais e commodities não classifi...   
13597  Operações especiais e commodities não classifi...   

                                           NO_CUCI_GRUPO  \
13593  Operações especiais e commodities não classifi...   
13594  Operações especiais e commodities não classifi...   
13595  Operações especiais e commodities não classifi...   
13596  Operações especiais e commodities não classifi...   
13597  Operações especiais e commodities não classifi...   

                                         NO_CUCI_DIVISAO  \
13593  Operações especiais e commodities não classifi...   
13594  Operações especiais e commodities não classifi...   
13595  Operações especiais e commodities não classifi...   
13596  Operações especiais e commodities não classifi...   
13597  Operações especiais e commodities não classifi...   

                                             NO_CUCI_SEC  
13593  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...  
13594  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...  
13595  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...  
13596  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...  
13597  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...

In [ ]:
df_isic.head()

CO_NCM  CO_ISIC_CLASSE                       NO_ISIC_CLASSE  \
0  1011010             142  Criação de cavalos e outros equinos   
1  1011090             142  Criação de cavalos e outros equinos   
2  1011100             142  Criação de cavalos e outros equinos   
3  1011900             142  Criação de cavalos e outros equinos   
4  1012000             142  Criação de cavalos e outros equinos   

     NO_ISIC_GRUPO                  NO_ISIC_DIVISAO NO_ISIC_SECAO  
0  Produção animal  Produção vegetal, animal e caça  Agropecuária  
1  Produção animal  Produção vegetal, animal e caça  Agropecuária  
2  Produção animal  Produção vegetal, animal e caça  Agropecuária  
3  Produção animal  Produção vegetal, animal e caça  Agropecuária  
4  Produção animal  Produção vegetal, animal e caça  Agropecuária

In [ ]:
#correlaçao isic seção com cuci grupo.
cod[15].CO_NCM.is_unique
cod[15].shape
cod[15].dtypes

CO_NCM            int64
NO_NCM_POR       object
CO_ISIC_SECAO    object
NO_ISIC_SECAO    object
CO_CUCI_GRUPO    object
NO_CUCI_GRUPO    object
dtype: object

In [ ]:
cod[4].CO_NCM.is_unique
cod[4].shape
cod[4].dtypes

CO_NCM         int64
NO_NCM_POR    object
CO_SIIT        int64
NO_SIIT       object
dtype: object

In [ ]:
#siit - setores industriais por intensidade tecnologia
df_siit = cod[4].loc[:,['CO_NCM','NO_SIIT']]
df_siit.shape

(13322, 2)

In [ ]:
cod[5].CO_NCM.is_unique
cod[5].shape
cod[5].dtypes
#as unidades foram traduzidas nas bases
len(pd.unique(cod[5].CO_UNID))
pd.unique(cod[5].NO_UNID)

array(['NUMERO (UNIDADE)', 'QUILOGRAMA LIQUIDO', 'DUZIA', 'GRAMA LIQUIDO',
       'TONELADA METRICA LIQUIDA', 'LITRO', 'MILHEIRO', 'METRO CUBICO',
       'MIL QUILOWATT HORA', 'QUILATE', 'METRO QUADRADO', 'METRO',
       'PARES'], dtype=object)

In [ ]:
#o fator de agregação está sendo descontinuado pelo sercretria, usar o isic no lugar, 
cod[6].CO_NCM.is_unique
cod[6].shape
cod[6].dtypes
pd.unique(cod[6].NO_FAT_AGREG)

array(['PRODUTOS BASICOS', 'PRODUTOS MANUFATURADOS',
       'PRODUTOS SEMIMANUFATURADOS', 'TRANSACOES ESPECIAIS',
       'CONSUMO DE BORDO', 'REEXPORTACAO'], dtype=object)

In [ ]:
cod[7].CO_NCM.is_unique
cod[8].CO_NCM.is_unique
cod[7].shape
cod[7].dtypes
cod[8].dtypes
pd.unique(cod[7].NO_PPI)
#ver quantas respostas unicas tem o atributo
len(pd.unique(cod[7].NO_PPI))
lista_imp = pd.unique(cod[7].NO_PPI).sort()
pd.unique(cod[8].NO_PPE)
len(pd.unique(cod[8].NO_PPE))
lista_exp = pd.unique(cod[8].NO_PPE).sort()

In [ ]:
#lista de paute de produtos para impotação é igual a de exportação
lista_imp == lista_exp
#tema mesma finalidade que a CGCE.

True

##montar df de paises e blocos

pais - nomes

In [ ]:
# cod[9] e cod[10] juntar o cod do país com nomo e bloco
cod[9].dtypes
cod[9].head()

In [ ]:
#ver colunas 
cod[9].dtypes 
#colunas a serem selecionas CO_PAIS NO_PAIS

# montar o dataframe com o nome e código de pais
dfpais = cod[9].loc[:,['CO_PAIS','NO_PAIS']]
dfpais.shape


(281, 2)

In [ ]:
#renoar as colunas
dfpais.rename(columns={ 'CO_PAIS': 'cod_pais', 'NO_PAIS':'pais'}, inplace=True)
dfpais

cod_pais                         pais
0           0                 Não Definido
1          13                  Afeganistão
2          15                 Aland, Ilhas
3          17                      Albânia
4          20       Alboran-Perejil, Ilhas
..        ...                          ...
276       994                   A Designar
277       995              Bancos Centrais
278       997  Organizações Internacionais
279       998               Sem informação
280       999               Não Declarados

[281 rows x 2 columns]

In [ ]:
#verificar se contem registros nulos
dfpais.isna().sum()

cod_pais    0
pais        0
dtype: int64

paises - blocos

In [ ]:
#só preciso do nome do país
cod[10].dtypes
cod[10].head()
#só preciso do nome do bloco
pd.unique(cod[10].NO_BLOCO)

array(['África', 'América Central e Caribe', 'América do Norte',
       'América do Sul', 'Ásia (Exclusive Oriente Médio)',
       'Associação de Nações do Sudeste Asiático - ASEAN', 'Europa',
       'Mercado Comum do Sul - Mercosul', 'Oceania', 'Oriente Médio',
       'União Europeia - UE'], dtype=object)

In [ ]:
cod[9].CO_PAIS.is_unique
cod[9].shape
#são 281 paises
cod[10].CO_PAIS.is_unique
#paises repetitos, separar os blocos geagraficos e economicos

False

In [ ]:
#voltei nesse comando
cod[9] = pd.read_excel(path, sheet_name=(10))
cod[10] = pd.read_excel(path, sheet_name=(11))

In [ ]:
#filtro para blocos geograficos
filtro_bl = cod[10].NO_BLOCO == ('África' or 'América Central e Caribe' or 'América do Norte' or
       'América do Sul' or 'Ásia (Exclusive Oriente Médio)' or 'Europa' or 'Oceania' or 'Oriente Médio')
dfbloc = cod[10].loc[filtro_bl]
dfbloc.CO_PAIS.is_unique

True

In [ ]:
#filtro de blocos economicos
filtro_ec = cod[10].NO_BLOCO == ('Associação de Nações do Sudeste Asiático - ASEAN' or 'Mercado Comum do Sul - Mercosul' or 'União Europeia - UE')
dfeco = cod[10].loc[filtro_ec]
dfeco.CO_PAIS.is_unique

True

In [ ]:
dfeco.dtypes #CO_PAIS NO_BLOCO
#cria o df de blocas economico
dfeco = dfeco.loc[:,['CO_PAIS', 'NO_BLOCO']]
#renomear as colunas
dfeco.rename(columns={'CO_PAIS': 'cod_pais','NO_BLOCO':'bloco_economico'}, inplace=True)
#cria o df de bloco geagroficos
dfbloc = dfbloc.loc[:,['CO_PAIS', 'NO_BLOCO']]
#renomear colunas
dfbloc.rename(columns={'CO_PAIS': 'cod_pais','NO_BLOCO':'bloco'}, inplace=True)

In [ ]:
# cod[11] e cod[12] fazer uma para o nome dos estados e região, e juntar ao nome do município da empresa?

In [ ]:
# cod[13]  é a tradução da via
# cod[14] é o nome dos urf

##juntas as classificaçõe em único df

In [ ]:
#juntar os cinco
# df_class = [df_sh, df_cuci, df_cgce, df_isic, df_siit]

In [ ]:
df_sh.dtypes

CO_NCM         int64
NO_NCM_POR    object
CO_SH6         int64
NO_SH6_POR    object
NO_SH4_POR    object
NO_SH2_POR    object
NO_SEC_POR    object
dtype: object

In [ ]:
#juntar os df_sh com df_cuci
df12 = pd.merge(df_sh, df_cuci, on='CO_NCM')
df12.shape

(13598, 13)

In [ ]:
#juntar ao anterior o df_cgce
df123 = pd.merge(df12, df_cgce, on='CO_NCM')
df123.shape

(13598, 17)

In [ ]:
#juntar ao anterior o df_isic
df1234 = pd.merge(df123, df_isic, on='CO_NCM')
df1234.shape

(13598, 22)

In [ ]:
#juntar ao antreior o df_siit
df_class = pd.merge(df1234, df_siit, on='CO_NCM')
df_class.shape

(13322, 23)

In [ ]:
#ver as informações do df pronto após todos os merges
df_class.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13322 entries, 0 to 13321
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   CO_NCM           13322 non-null  int64 
 1   NO_NCM_POR       13322 non-null  object
 2   CO_SH6           13322 non-null  int64 
 3   NO_SH6_POR       13322 non-null  object
 4   NO_SH4_POR       13322 non-null  object
 5   NO_SH2_POR       13322 non-null  object
 6   NO_SEC_POR       13322 non-null  object
 7   CO_CUCI_ITEM     13322 non-null  object
 8   NO_CUCI_ITEM     13322 non-null  object
 9   NO_CUCI_SUB      13322 non-null  object
 10  NO_CUCI_GRUPO    13322 non-null  object
 11  NO_CUCI_DIVISAO  13322 non-null  object
 12  NO_CUCI_SEC      13322 non-null  object
 13  CO_CGCE_N3       13322 non-null  int64 
 14  NO_CGCE_N3       13322 non-null  object
 15  NO_CGCE_N2       13322 non-null  object
 16  NO_CGCE_N1       13322 non-null  object
 17  CO_ISIC_CLASSE   13322 non-null

In [ ]:
df_class.tail()

CO_NCM                                       NO_NCM_POR  CO_SH6  \
13317  99997103          Joalheria de ouro do capitulo 71 da NCM  999971   
13318  99997104             Outros artigos do capitulo 71 da NCM  999971   
13319  99999900  Qualquer outra mercadoria sem cobertura cambial  999999   
13320  99999951    Devolução antes da DI (exportação definitiva)  999999   
13321  99999960                                     Reexportação  999999   

                                              NO_SH6_POR  \
13317    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13318    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13319  Qualquer outra mercadoria sem cobertura cambia...   
13320  Qualquer outra mercadoria sem cobertura cambia...   
13321  Qualquer outra mercadoria sem cobertura cambia...   

                                              NO_SH4_POR  \
13317  Consumo de bordo (exceto combustíveis e lubrif...   
13318  Consumo de bordo (exceto combustíveis e lubrif...   
13319  Consumo de bordo (exceto combustíveis e lubrif...   
13320  Consumo de bordo (exceto combustíveis e lubrif...   
13321  Consumo de bordo (exceto combustíveis e lubrif...   

                 NO_SH2_POR            NO_SEC_POR CO_CUCI_ITEM  \
13317  Transações especiais  Transações especiais         9310   
13318  Transações especiais  Transações especiais         9310   
13319  Transações especiais  Transações especiais         9310   
13320  Transações especiais  Transações especiais         9310   
13321  Transações especiais  Transações especiais         9310   

                                            NO_CUCI_ITEM  \
13317  Operações especiais e commodities não classifi...   
13318  Operações especiais e commodities não classifi...   
13319  Operações especiais e commodities não classifi...   
13320  Operações especiais e commodities não classifi...   
13321  Operações especiais e commodities não classifi...   

                                             NO_CUCI_SUB  \
13317  Operações especiais e commodities não classifi...   
13318  Operações especiais e commodities não classifi...   
13319  Operações especiais e commodities não classifi...   
13320  Operações especiais e commodities não classifi...   
13321  Operações especiais e commodities não classifi...   

                                           NO_CUCI_GRUPO  \
13317  Operações especiais e commodities não classifi...   
13318  Operações especiais e commodities não classifi...   
13319  Operações especiais e commodities não classifi...   
13320  Operações especiais e commodities não classifi...   
13321  Operações especiais e commodities não classifi...   

                                         NO_CUCI_DIVISAO  \
13317  Operações especiais e commodities não classifi...   
13318  Operações especiais e commodities não classifi...   
13319  Operações especiais e commodities não classifi...   
13320  Operações especiais e commodities não classifi...   
13321  Operações especiais e commodities não classifi...   

                                             NO_CUCI_SEC  CO_CGCE_N3  \
13317  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...         311   
13318  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...         322   
13319  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...         999   
13320  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...         999   
13321  MERCADORIAS E TRANSACOES NAO ESPECIFICADAS EM ...         999   

                                              NO_CGCE_N3  \
13317  Bens de consumo duráveis – exceto equipamentos...   
13318                       Bens de consumo não duráveis   
13319               Bens não especificados anteriormente   
13320               Bens não especificados anteriormente   
13321               Bens não especificados anteriormente   

                                        NO_CGCE_N2  \
13317                     Bens de consumo duráveis   
13318  Bens de consumo semiduráveis e não duráveis   
13319         Bens não especifica

##esquema para o spark

In [ ]:
df_class.dtypes

ano	mes	mercadoria	ncm_unidade	estado	meio_transporte	urf_localizacao	qnt_estatistica	peso_liquido	valor_dolar	pais

In [ ]:
# Preparar schema para importar dataframe (StructTypes)

esquema = (
    StructType([
        StructField('ncm', IntegerType()),
        StructField('produto', StringType()),
        StructField('sh6', IntegerType()),
        StructField('sh6_mercadoria', StringType()),
        StructField('sh4_posicao', StringType()),
        StructField('sh6_capitulo', StringType()),
        StructField('sh6_secao', StringType()),
        StructField('cuci', StringType()),
        StructField('cuci_item', StringType()),
        StructField('cuci_subgrupo', StringType()),
        StructField('cuci_grupo', StringType()),
        StructField('cuci_divisao', StringType()),
        StructField('cuci_secao', StringType()),
        StructField('cgce', IntegerType()),
        StructField('cgce_economica_n3', StringType()),
        StructField('cgce_n2', StringType()),
        StructField('cgce_n1', StringType()),
        StructField('isic', IntegerType()),
        StructField('isic_class_industrial', StringType()),
        StructField('isic_grupo', StringType()),
        StructField('isic_divisao', StringType()),
        StructField('isic_secao', StringType()),
        StructField('siit_setor_industrial', StringType()),
    ])
)

In [ ]:
# Conversão para PySpark (utilizando schema definido - o que renomeará as colunas)
dfcat = spark.createDataFrame(df_class, schema = esquema)

In [ ]:
dfcat.describe()

DataFrame[summary: string, ncm: string, produto: string, sh6: string, sh6_mercadoria: string, sh4_posicao: string, sh6_capitulo: string, sh6_secao: string, cuci: string, cuci_item: string, cuci_subgrupo: string, cuci_grupo: string, cuci_divisao: string, cuci_secao: string, cgce: string, cgce_economica_n3: string, cgce_n2: string, cgce_n1: string, isic: string, isic_class_industrial: string, isic_grupo: string, isic_divisao: string, isic_secao: string, siit_setor_industrial: string]

In [ ]:
dfcat.show()

+-------+--------------------+-----+--------------------+--------------------+-------------+--------------------+-----+--------------------+--------------------+--------------------+--------------------+--------------------+----+--------------------+--------------------+--------------------+----+---------------------+---------------+--------------------+------------+---------------------+
|    ncm|             produto|  sh6|      sh6_mercadoria|         sh4_posicao| sh6_capitulo|           sh6_secao| cuci|           cuci_item|       cuci_subgrupo|          cuci_grupo|        cuci_divisao|          cuci_secao|cgce|   cgce_economica_n3|             cgce_n2|             cgce_n1|isic|isic_class_industrial|     isic_grupo|        isic_divisao|  isic_secao|siit_setor_industrial|
+-------+--------------------+-----+--------------------+--------------------+-------------+--------------------+-----+--------------------+--------------------+--------------------+--------------------+-------------

In [ ]:
#salvar um df spark
dfcat.write.format('csv').mode('overwrite').save('/content')

##voltar pro pandas renomeado

In [ ]:
#converte o dataframe spakr para pandas
df = dfcat.toPandas()
df.shape

(13322, 23)

In [ ]:
df

ncm                                            produto     sh6  \
0       1011010                  Cavalos reprodutores de raça pura   10110   
1       1011090  Animais da espécie asinina/muar, reprodutores,...   10110   
2       1011100                 Cavalos reprodutores, de raça pura   10111   
3       1011900                              Outros cavalos, vivos   10119   
4       1012000                            Asininos e muares vivos   10120   
...         ...                                                ...     ...   
13317  99997103            Joalheria de ouro do capitulo 71 da NCM  999971   
13318  99997104               Outros artigos do capitulo 71 da NCM  999971   
13319  99999900    Qualquer outra mercadoria sem cobertura cambial  999999   
13320  99999951      Devolução antes da DI (exportação definitiva)  999999   
13321  99999960                                       Reexportação  999999   

                                          sh6_mercadoria  \
0      Animais vivos das espécies cavalar, asinina e ...   
1      Animais vivos das espécies cavalar, asinina e ...   
2                     Cavalos reprodutores, de raça pura   
3                                  Outros cavalos, vivos   
4                                Asininos e muares vivos   
...                                                  ...   
13317    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13318    Pedras, em bruto ou trabalhadas, do Capítulo 71   
13319  Qualquer outra mercadoria sem cobertura cambia...   
13320  Qualquer outra mercadoria sem cobertura cambia...   
13321  Qualquer outra mercadoria sem cobertura cambia...   

                                             sh4_posicao  \
0                      Cavalos, asininos e muares, vivos   
1                      Cavalos, asininos e muares, vivos   
2                      Cavalos, asininos e muares, vivos   
3                      Cavalos, asininos e muares, vivos   
4                      Cavalos, asininos e muares, vivos   
...                                                  ...   
13317  Consumo de bordo (exceto combustíveis e lubrif...   
13318  Consumo de bordo (exceto combustíveis e lubrif...   
13319  Consumo de bordo (exceto combustíveis e lubrif...   
13320  Consumo de bordo (exceto combustíveis e lubrif...   
13321  Consumo de bordo (exceto combustíveis e lubrif...   

               sh6_capitulo                                 sh6_secao  cuci  \
0             Animais vivos  Animais vivos e produtos do reino animal  0015   
1             Animais vivos  Animais vivos e produtos do reino animal  0015   
2             Animais vivos  Animais vivos e produtos do reino animal  0015   
3             Animais vivos  Animais vivos e produtos do reino animal  0015   
4             Animais vivos  Animais vivos e produtos do reino animal  0015   
...                     ...                                       ...   ...   
13317  Transações especiais                      Transações especiais  9310   
13318  Transações especiais                      Transações especiais  9310   
13319  Transações especiais                      Transações especiais  9310   
13320  Transações especiais                      Transações especiais  9310   
13321  Transações especiais                      Transações especiais  9310   

                                               cuci_item  \
0                   Cavalos, asnos, mulas e burros vivos   
1                   Cavalos, asnos, mulas e burros vivos   
2                   Cavalos, asnos, mulas e burros vivos   
3                   Cavalos, asnos, mulas e burros vivos   
4                   Cavalos, asnos, mulas e burros vivos   
...                                                  ...   
13317  Operações especiais e commodities não classifi...   
13318  Operações especiais e commodities não classifi...   
13319  Operações especiais e commodities não classifi...   
13320  Operações especiais e commodities não classifi...   
13321  Operações especia

In [ ]:
# df.drop_duplicates()

##salvar e enviar ao bucket

In [ ]:
#salvar
df.to_csv('imp-exp-classificacoes.csv',index=False)

dfpais.to_csv('nome-pais.csv',index=False)

In [ ]:
#salvar as duas bases com os blocos
dfeco.to_csv('bloco-economico.csv',index=False)
dfbloc.to_csv('bloco-geagrofico.csv',index=False)

In [ ]:
#enviar para a bucket
bucket.blob('comex-tratado/imp-exp-classificacoes').upload_from_filename('/content/imp-exp-classificacoes.csv')

In [ ]:
#enviar para a bucket
bucket.blob('comex-tratado/nome-pais').upload_from_filename('/content/nome-pais.csv')

In [ ]:
bucket.blob('comex-tratado/bloco-economico').upload_from_filename('/content/bloco-economico.csv')
bucket.blob('comex-tratado/bloco-geografico').upload_from_filename('/content/bloco-geagrofico.csv')

#Conexão com o Big Query

 Envio do dataframe tratado para BigQuerry (utilizando Pandas) - cod Marcos



In [ ]:
# Chave de acesso ao BigQuery com as seguintes roles: Big Query User e Big Query Data Editor
key_path= "/content/chave_bigquery_JSON.json"

# Variável credentials
credentials = service_account.Credentials.from_service_account_file(
        key_path, scopes=["https://www.googleapis.com/auth/cloud-platform"])

pandas_gbq.context.credentials = credentials
pandas_gbq.context.project = "bc26-ed7-projeto-final"

#enviar base de auxilio

In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'imp-exp-classificaçoes')

pandas_gbq.to_gbq(df, 'comercio_brasil.imp-exp-classificacoes', project_id='bc26-ed7-projeto-final', if_exists='replace')

# OK

100%|██████████| 1/1 [00:00<00:00, 6743.25it/s]


In [ ]:
df.shape

(13322, 23)

##enviar a base com os nomes de paises para o big query

In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'nome-pais')
pandas_gbq.to_gbq(dfpais, 'comercio_brasil.nome_pais', project_id='bc26-ed7-projeto-final', if_exists='replace')


100%|██████████| 1/1 [00:00<00:00, 8405.42it/s]


In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'nome-pais')
pandas_gbq.to_gbq(dfblco, 'comercio_brasil.contimente', project_id='bc26-ed7-projeto-final', if_exists='replace')


100%|██████████| 1/1 [00:00<00:00, 7884.03it/s]


In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'nome-pais')
pandas_gbq.to_gbq(dfecom, 'comercio_brasil.bloco_ecomonico', project_id='bc26-ed7-projeto-final', if_exists='replace')


100%|██████████| 1/1 [00:00<00:00, 7096.96it/s]


codigos usado no bq

In [ ]:
#SELECT * FROM `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` WHERE sh6_posicao = 'Polímeros de etileno, em formas primárias'

In [ ]:
#SELECT distinct(produto) FROM `bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022` LIMIT 1000

In [ ]:
# spark.sql('SELECT * FROM dfcat WHERE sh6_posicao =="Polímeros de etileno, em formas primárias"')

In [ ]:
#enviar a base com o nome dos paises
pandas_gbq.to_gbq(dfpais, 'comercio_brasil.pais', project_id='bc26-ed7-projeto-final', if_exists='replace')

In [ ]:
#enviar as base de paises para agrupamento
pandas_gbq.to_gbq(dfbloc, 'comercio_brasil.bloco', project_id='bc26-ed7-projeto-final', if_exists='replace')
pandas_gbq.to_gbq(dfeco, 'comercio_brasil.bloco-economico', project_id='bc26-ed7-projeto-final', if_exists='replace')

#3 caminho para as bases tratades em parquet e cvs

In [ ]:
#Caminho das base no bucket
#tratada
path_imp_mun = 'gs://bc26-datasets-comex/comex-tratado/IMP_2012-2022_tratada (MUN).parquet'
path_imp_prod = 'gs://bc26-datasets-comex/comex-tratado/IMP_2012-2022_tratada (NCM).parquet'
path_exp_mun = 'gs://bc26-datasets-comex//comex-tratado/EXP_2012_2022_tratado(MUN).parquet'
path_exp_prod = 'gs://bc26-datasets-comex/comex-tratado/EXP_2012_2022_tratado(NCM).parquet'

#tradato - checar o link
path_comb_preco = 'gs://bc26-datasets-comex/preco-combustiveis-2013-2022-TRATADO'
path_comb_vol = 'bc26-datasets-comex/combustivel-tratado/vendas-combustiveis-2013-2022' 
#base de categorias
path_cat = 'gs://bc26-datasets-comex/comex-tratado/imp-exp-classificacoes'

In [ ]:
# que base é essa?
path_comex = 'gs://bc26-datasets-comex/bc26-datasets-comex/comex-tratado'

In [ ]:
#Caminho das base no bucket - minha nova versão

#tratada importação
path_imp_mun = 'gs://bc26-datasets-comex/comex-tratado/IMP_2012-2022_tratada (MUN).parquet'
path_imp_prod = 'gs://bc26-datasets-comex/comex-tratado/IMP_2012-2022_tratada (NCM).parquet'

#tratada exportação 
path_exp_mun = 'gs://bc26-datasets-comex/comex-tratado/IMP_2012-2022_tratada (MUN).parquet'

path_exp_prod = 'gs://bc26-datasets-comex/comex-tratado/EXP_2013-2022_tratado(NCM).csv'

#tratada combustíveis
path_comb = 'gs://bc26-datasets-comex/preco-combustiveis-2013-2022-TRATAMENTO-OK'
#tratasa combustívies com volume
path_comb_vol = 'gs://bc26-datasets-comex/combustivel-tratado/volume_preco_combustiveis_mensal_2013_2022' 


#Enviar a base de exportação para o BQ

In [ ]:
#criar o dataframe de exportação por municipios
df_em = pd.read_parquet(path_exp_mun)
df_em.head(2)

mes   SH4  cod_pais estado  cod_municipio  peso_liquido  valor_dolar  \
0    janeiro  6115       160     RS        4314902          2512        37327   
1  fevereiro  8481        23     RS        4314902            80         8444   

                     descricoes__sistema_harmonizado     municipio   ano  
0          Polímeros de etileno, em formas primárias  Porto Alegre  2012  
1  Fatos de saia-casaco, conjuntos, casacos, vest...  Porto Alegre  2012

In [ ]:
df_em.dtypes


mes                                  object
SH4                                   int64
cod_pais                              int64
estado                               object
cod_municipio                         int64
peso_liquido                          int64
valor_dolar                           int64
descricoes__sistema_harmonizado      object
municipio                            object
ano                                category
dtype: object

In [ ]:
df_em['ano'] = df_em['ano'].astype(int)

In [ ]:
df_em.dtypes

mes                                object
SH4                                 int64
cod_pais                            int64
estado                             object
cod_municipio                       int64
peso_liquido                        int64
valor_dolar                         int64
descricoes__sistema_harmonizado    object
municipio                          object
ano                                 int64
dtype: object

In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'exp_2012-2022_tratada_mun')

pandas_gbq.to_gbq(df_em, 'comercio_brasil.exp_2012-2022_tratada_mun', project_id='bc26-ed7-projeto-final', if_exists='replace')


100%|██████████| 1/1 [00:00<00:00, 6423.13it/s]


In [ ]:
#criar o dataframe de exportação por produto, com a nomeclaruta do mercosul
df_ep = pd.read_csv(path_exp_prod)
df_ep.head(2)

ano      mes  cod_mercadoria             unidade  cod_pais estado  \
0  2013    Março        30067000  Quilograma líquido       169     SP   
1  2013  Janeiro        30067000  Quilograma líquido       493     SP   

  meio_transporte  cod_urf  qnt_estatistica  peso_liquido  valor_dolar  \
0        Marítima   817800             1447          1447        27538   
1        Marítima   817800             1512          1512        26435   

     urf_localizacao                                         mercadoria  
0    PORTO DE SANTOS  Preparações em gel, utilizadas em intervenção ...  
1    PORTO DE SANTOS  Preparações em gel, utilizadas em intervenção ...

In [ ]:
df_ep.dtypes

ano                 int64
mes                object
cod_mercadoria      int64
unidade            object
cod_pais            int64
estado             object
meio_transporte    object
cod_urf             int64
qnt_estatistica     int64
peso_liquido        int64
valor_dolar         int64
urf_localizacao    object
mercadoria         object
dtype: object

In [ ]:
# Envio para BigQuerry (dataset = 'comercio-brasil / tabela = 'exp_2012-2022_tratada_ncm')

pandas_gbq.to_gbq(df_ep, 'comercio_brasil.exp_2012-2022_tratada_ncm', project_id='bc26-ed7-projeto-final', if_exists='replace')

# OK

100%|██████████| 1/1 [00:00<00:00, 7269.16it/s]


In [ ]:
#por capcidade de  tamanho apagar
# del df_em

bases importação

In [ ]:
#criar dataframe com as importações por município
df_im = pd.read_parquet(path_im)
df_im.head(2)

mes   SH4  cod_pais estado  cod_municipio  peso_liquido  valor_dolar  \
0    janeiro  6115       160     RS        4314902          2512        37327   
1  fevereiro  8481        23     RS        4314902            80         8444   

                     descricoes__sistema_harmonizado     municipio   ano  
0          Polímeros de etileno, em formas primárias  Porto Alegre  2012  
1  Fatos de saia-casaco, conjuntos, casacos, vest...  Porto Alegre  2012

In [ ]:
#criar o dataframe com as importações por produtos
df_ip = pd.read_parquet(path_ip)
df_ip.head(2)

mes  mercadoria  cod_unidade  cod_pais estado  cod_urf  qnt_estatistica  \
0  março    39095021           10       190     CE   317700              211   
1  junho    39095021           10       245     RS  1017600               50   

   peso_liquido  valor_dolar  \
0           211         3600   
1            50          459   

                                             produto    unidade_medida  \
0  Poliuretanos hidroxilados, com propriedades ad...  NUMERO (UNIDADE)   
1  Poliuretanos hidroxilados, com propriedades ad...  NUMERO (UNIDADE)   

  meio_transporte   ano  
0           AEREA  2012  
1           AEREA  2012

base preço do combustivel

In [ ]:
#criar o dataframe com os preço dos combustivies
df_comb = pd.read_parquet(path_comb)
df_comb.head(2)

data_inicial  data_final        regiao            estado  \
0   2012-12-30  2013-01-05  CENTRO OESTE  DISTRITO FEDERAL   
1   2012-12-30  2013-01-05  CENTRO OESTE             GOIAS   

               municipio           produto  num_postos_pesquisados  \
0               BRASILIA  ETANOL HIDRATADO                      80   
1  AGUAS LINDAS DE GOIAS  ETANOL HIDRATADO                       5   

  unidade_medida  preco_medio_revenda  desvio_padrao_revenda  \
0           R$/l                2.273                  0.023   
1           R$/l                2.134                  0.043   

   preco_min_revenda  preco_max_revenda  margem_media_revenda  \
0               2.19              2.299                 0.405   
1               2.09              2.190                 0.268   

   coef_variacao_revenda  
0                   0.01  
1                   0.02

In [ ]:
# del df_ep

In [ ]:
df_em

base de auxilio

In [ ]:
path_pais = 'gs://bc26-datasets-comex/comex-tratado/nome-pais'
path_bloco = 'gs://bc26-datasets-comex/comex-tratado/bloco-economico'
path_ecom = 'gs://bc26-datasets-comex/comex-tratado/bloco-geografico'

In [ ]:
df_pais = pd.read_csv(path_pais)
df_blco = pd.read_csv(path_bloco)
df_ecom = pd.read_csv(path_ecom)

In [ ]:
df_pais.tail()

cod_pais                         pais
276       994                   A Designar
277       995              Bancos Centrais
278       997  Organizações Internacionais
279       998               Sem informação
280       999               Não Declarados

#filtro de combustivel na bases de exp/imp produtos

Carregamento das bases

In [ ]:
df_comb = pd.read_parquet(path_comb)

In [ ]:
dfcat = ( spark.read.format('csv')
                 .option('header', 'true')
                 .option('inferschema', 'true')
                 .option('delimiter', ',')
                 .load(path_cat))

In [ ]:
df = pd.read_csv(path_cat)

##procurar os ncm e sh para combustiveis.

In [ ]:
combustiveis = pd.unique(df_comb.produto)

In [ ]:
print(combustiveis)

['ETANOL HIDRATADO' 'GASOLINA COMUM' 'GLP' 'GNV' 'OLEO DIESEL'
 'OLEO DIESEL S10' 'GASOLINA ADITIVADA']


In [ ]:
# dfcat.show(2)
df.head(2)

ncm                                            produto    sh6  \
0  1011010                  Cavalos reprodutores de raça pura  10110   
1  1011090  Animais da espécie asinina/muar, reprodutores,...  10110   

                                      sh6_mercadoria  \
0  Animais vivos das espécies cavalar, asinina e ...   
1  Animais vivos das espécies cavalar, asinina e ...   

                         sh6_posicao   sh6_capitulo  \
0  Cavalos, asininos e muares, vivos  Animais vivos   
1  Cavalos, asininos e muares, vivos  Animais vivos   

                                  sh6_secao  cuci  \
0  Animais vivos e produtos do reino animal  0015   
1  Animais vivos e produtos do reino animal  0015   

                              cuci_item                         cuci_subgrupo  \
0  Cavalos, asnos, mulas e burros vivos  Cavalos, asnos, mulas e burros vivos   
1  Cavalos, asnos, mulas e burros vivos  Cavalos, asnos, mulas e burros vivos   

                                          cuci_grupo  \
0  Animais vivos, não incluído pescados ou crustá...   
1  Animais vivos, não incluído pescados ou crustá...   

                                 cuci_divisao  \
0  Animais vivos não incluídos no capítulo 03   
1  Animais vivos não incluídos no capítulo 03   

                              cuci_secao  cgce  \
0  PRODUTOS ALIMENTICIOS E ANIMAIS VIVOS   110   
1  PRODUTOS ALIMENTICIOS E ANIMAIS VIVOS   110   

                                   cgce_economica_n3  \
0  Bens de capital (exceto equipamentos de transp...   
1  Bens de capital (exceto equipamentos de transp...   

                                             cgce_n2               cgce_n1  \
0  Bens de capital, exceto equipamentos de transp...  BENS DE CAPITAL (BK)   
1  Bens de capital, exceto equipamentos de transp...  BENS DE CAPITAL (BK)   

   isic                isic_class_industrial       isic_grupo  \
0   142  Criação de cavalos e outros equinos  Produção animal   
1   142  Criação de cavalos e outros equinos  Produção animal   

                      isic_divisao    isic_secao siit_setor_industrial  
0  Produção vegetal, animal e caça  Agropecuária      PRODUTOS N.C.I.T  
1  Produção vegetal, animal e caça  Agropecuária      PRODUTOS N.C.I.T

In [ ]:
filtro_comb_ncm = df.produto.str.contains('etanol | gasolina | GLP | GNV | diesel')
filtro_comb_sh = df.sh6_mercadoria.str.contains('etanol | gasolina | GLP | GNV | diesel') 
#resultado muito amplo

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
1864   26202100            Lamas de gasolina contendo chumbo, etc.  262021   
1916   27100041                              Gasóleo (óleo diesel)  271000   
1951   27101921                              Gasóleo (óleo diesel)  271019   
2724   29051100                          Metanol (álcool metílico)  290511   
2856   29094100                 2,2'-Oxidietanol (dietilenoglicol)  290941   
...         ...                                                ...     ...   
12272  87042290  Outros veículos automóveis com motor diesel, c...  870422   
12273  87042310  Chassis com motor diesel e cabina, capacidade ...  870423   
12274  87042320  Veículos automóveis com motor diesel, caixa ba...  870423   
12275  87042330  Veículos automóveis frigoríficos com motor die...  870423   
12277  87042390  Outros veículos automóveis motor diesel, carga...  870423   

                                          sh6_mercadoria  \
1864   Lamas de gasolina e de compostos antidetonante...   
1916   Naftas, gasolinas, querosenes, gasóleo, outros...   
1951   Outros óleos de petróleo ou de minerais betumi...   
2724                           Metanol (álcool metílico)   
2856                   2,2-Oxidietanol (dietilenoglicol)   
...                                                  ...   
12272  Veículos automóveis para transporte de mercado...   
12273  Veículos automóveis para transporte de mercado...   
12274  Veículos automóveis para transporte de mercado...   
12275  Veículos automóveis para transporte de mercado...   
12277  Veículos automóveis para transporte de mercado...   

                                             sh6_posicao  \
1864   Cinzas e resíduos (exceto provenientes da fabr...   
1916   Óleos de petróleo ou de minerais betuminosos, ...   
1951   Óleos de petróleo ou de minerais betuminosos, ...   
2724   Álcoois acíclicos e seus derivados halogenados...   
2856   Éteres, éteres-álcoois, éteres-fenóis, éteres-...   
...                                                  ...   
12272  Veículos automóveis para transporte de mercado...   
12273  Veículos automóveis para transporte de mercado...   
12274  Veículos automóveis para transporte de mercado...   
12275  Veículos automóveis para transporte de mercado...   
12277  Veículos automóveis para transporte de mercado...   

                                            sh6_capitulo  \
1864                         Minerios, escórias e cinzas   
1916   Combustíveis minerais, óleos minerais e produt...   
1951   Combustíveis minerais, óleos minerais e produt...   
2724                         Produtos químicos orgânicos   
2856                         Produtos químicos orgânicos   
...                                                  ...   
12272  Veículos automóveis, tratores, ciclos e outros...   
12273  Veículos automóveis, tratores, ciclos e outros...   
12274  Veículos automóveis, tratores, ciclos e outros...   
12275  Veículos automóveis, tratores, ciclos e outros...   
12277  Veículos automóveis, tratores, ciclos e outros...   

                                               sh6_secao   cuci  \
1864                                   Produtos minerais   2881   
1916                                   Produtos minerais   3346   
1951                                   Produtos minerais   3346   
2724   Produtos das indústrias químicas ou indústrias...  51211   
2856   Produtos das indústrias químicas ou indústrias...  51617   
...                                                  ...    ...   
12272                             Material de transporte  78219   
12273                             Material de transporte  78219   
12274                             Material de transporte  78219   
12275                             Material de transporte  78219   
12277                             Material de transporte  78219   

                                               cuci_item  \
1864   Cinzas e resíduos (exceto os proveniente

In [ ]:
df.loc[filtro_comb_sh]

ncm                                            produto     sh6  \
1864   26202100            Lamas de gasolina contendo chumbo, etc.  262021   
2724   29051100                          Metanol (álcool metílico)  290511   
2856   29094100                 2,2'-Oxidietanol (dietilenoglicol)  290941   
9864   84081010  Motores diesel/semidiesel, para embarcação, ti...  840810   
9865   84081090  Outros motores diesel/semidiesel, para embarcação  840810   
9866   84082010  Motores diesel/semidiesel, para vículos do cap...  840820   
9867   84082020  Motores diesel/semidiesel, para veículos do ca...  840820   
9868   84082030  Motores diesel/semidiesel, para veículos do ca...  840820   
9869   84082090  Outros motores diesel/semidiesel, para veículo...  840820   
9870   84089010  Outros motores diesel, estacionários, potência...  840890   
9871   84089090                   Outros motores diesel/semidiesel  840890   
9885   84099911           Bielas para motores diesel ou semidiesel  840999   
9886   84099912  Blocos de cilindros, cabeçotes, etc, para moto...  840999   
9887   84099913        Injetores para motores diesel ou semidiesel  840999   
9888   84099914  Válvulas de admissão ou de escape, para motore...  840999   
9889   84099915  Coletores de admissão ou escape, para motores ...  840999   
9890   84099916  Anéis de segmento, para motores a diesel ou se...  840999   
9891   84099917  Guias de válvulas, para motores diesel ou semi...  840999   
9892   84099920  Pistões ou embolos, para motores diesel ou sem...  840999   
9893   84099921  Pistões/embolos, com diâmetro superior ou igua...  840999   
9894   84099929  Outros pistões ou embolos, para motores diesel...  840999   
9895   84099930  Camisas de cilindro, para motores diesel ou se...  840999   
9896   84099941  Bielas com peso superior ou igual a 30 kg, par...  840999   
9897   84099949      Outras bielas, para motores diesel/semidiesel  840999   
9898   84099951  Cabeçotes, com diâmetro superior ou igual a 20...  840999   
9899   84099959    Outros cabeçotes para motores diesel/semidiesel  840999   
9900   84099961  Injetores/bicos injetores, com diâmetro superi...  840999   
9901   84099969    Outros injetores para motores diesel/semidiesel  840999   
9902   84099971  Anéis de segmento, com diâmetro superior ou ig...  840999   
9903   84099979  Outros anéis de segmento, para motores diesel/...  840999   
9904   84099990    Outras partes para motores diesel ou semidiesel  840999   
9905   84099991  Camisas de cilindro soldadas a cabeçotes, com ...  840999   
9906   84099999     Outras partes para motores diesel e semidiesel  840999   
12190  86021000                       Locomotivas diesel-elétricas  860210   

                                          sh6_mercadoria  \
1864   Lamas de gasolina e de compostos antidetonante...   
2724                           Metanol (álcool metílico)   
2856                   2,2-Oxidietanol (dietilenoglicol)   
9864   Motores de pistão, de ignição por compressão, ...   
9865   Motores de pistão, de ignição por compressão, ...   
9866   Motores de pistão, de ignição por compressão, ...   
9867   Motores de pistão, de ignição por compressão, ...   
9868   Motores de pistão, de ignição por compressão, ...   
9869   Motores de pistão, de ignição por compressão, ...   
9870   Outros motores de pistão, de ignição por compr...   
9871   Outros motores de pistão, de ignição por compr...   
9885     Outras partes para motores diesel ou semidiesel   
9886     Outras partes para motores diesel ou semidiesel   
9887     Outras partes para motores diesel ou semidiesel   
9888     Outras partes para motores diesel ou semidiesel   
9889     Outras partes para motores diesel ou semidiesel   
9890     Outras partes para motores diesel ou semidiesel   
9891     Outras partes para motores diesel ou semidiesel   
9892     Outras partes para motores diesel ou semidiesel   
9893     Outras partes para motores diesel ou semidiesel   
9894     Outras parte

In [ ]:
filtro_comb_ncm = df.produto.str.contains('etanol')
filtro_comb_sh = df.sh6_mercadoria.str.contains('etanol')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
2724  29051100                          Metanol (álcool metílico)  290511   
2785  29062910                                      2-feniletanol  290629   
2856  29094100                 2,2'-Oxidietanol (dietilenoglicol)  290941   
3380  29221100                        Monoetanolamina e seus sais  292211   
3381  29221200                          Dietanolamina e seus sais  292212   
3382  29221310                                     Trietanolamina  292213   
3383  29221320                             Sais de trietanolamina  292213   
3385  29221500                                     Trietanolamina  292215   
3386  29221600         Perfluoroctanossulfonato de dietanolamônio  292216   
3387  29221700             Metildietanolamina e etildietanolamina  292217   
3388  29221800                     2-(N,N-diisopropilamino)etanol  292218   
3399  29221951  N, n-dimetil-2-aminoetanol e seus sais protonados  292219   
3400  29221952    N,N-Dietil-2-aminoetanol e seus sais protonados  292219   
3401  29221959  Outros n, n-dialquil-2-aminoetanol, seus sais ...  292219   
3402  29221961          Metildietanolamina e seus sais protonados  292219   
3403  29221962           Etildietanolamina e seus sais protonados  292219   
3404  29221969  Outros n-alquil-dietanolamina e seus sais prot...  292219   
3500  29241094       Dietanolamidas de ácidos graxos de c12 a c18  292410   
3522  29241994       Dietanolamidas de ácidos graxos de c12 a c18  292419   
3627  29280030                                  2-hidrazinoetanol  292800   
3679  29309031  2-(Etiltio)etanol, com uma concentração superi...  293090   
5976  38249085                       Metilato de sódio em metanol  382490   
6024  38249985                       Metilato de sódio em metanol  382499   
6188  39079993  Copolímero de tereftalato de dimetila, cicloex...  390799   
6189  39079994  Copolímero de tereftalato de dimetila, cicloex...  390799   
6190  39079995  Copolímero de tereftalato de dimetila, cicloex...  390799   

                                         sh6_mercadoria  \
2724                          Metanol (álcool metílico)   
2785  Outros álcoois cíclicos aromáticos e seus deri...   
2856                  2,2-Oxidietanol (dietilenoglicol)   
3380                        Monoetanolamina e seus sais   
3381                          Dietanolamina e seus sais   
3382                         Trietanolamina e seus sais   
3383                         Trietanolamina e seus sais   
3385                                     Trietanolamina   
3386         Perfluoroctanossulfonato de dietanolamônio   
3387             Metildietanolamina e etildietanolamina   
3388                     2-(N,N-diisopropilamino)etanol   
3399   Outros aminoálcoois, seus éteres, ésteres e sais   
3400   Outros aminoálcoois, seus éteres, ésteres e sais   
3401   Outros aminoálcoois, seus éteres, ésteres e sais   
3402   Outros aminoálcoois, seus éteres, ésteres e sais   
3403   Outros aminoálcoois, seus éteres, ésteres e sais   
3404   Outros aminoálcoois, seus éteres, ésteres e sais   
3500       Amidas acíclicos e seus derivados, seus sais   
3522  Outras amidas acíclicas (incluídos os carbomat...   
3627   Derivados orgânicos da hidrazina e hidroxilamina   
3679                      Outros tiocompostos orgânicos   
5976  Outros produtos e preparações das indústrias q...   
6024  Outros aglutinantes preparados para moldes ou ...   
6188            Outros poliésteres, em formas primárias   
6189            Outros poliésteres, em formas primárias   
6190            Outros poliésteres, em formas primárias   

                                            sh6_posicao  \
2724  Álcoois acíclicos e seus derivados halogenados...   
2785  Álcoois cíclicos e seus derivados halogenados,...   
2856  Éteres, éteres-álcoois, éteres-fenóis, éteres-...   
3380           Compostos aminados de funções oxigenadas   
3381           Compostos aminados de funçõ

In [ ]:
df.loc[filtro_comb_sh]

ncm                                     produto     sh6  \
2724  29051100                   Metanol (álcool metílico)  290511   
2856  29094100          2,2'-Oxidietanol (dietilenoglicol)  290941   
3380  29221100                 Monoetanolamina e seus sais  292211   
3381  29221200                   Dietanolamina e seus sais  292212   
3382  29221310                              Trietanolamina  292213   
3383  29221320                      Sais de trietanolamina  292213   
3385  29221500                              Trietanolamina  292215   
3386  29221600  Perfluoroctanossulfonato de dietanolamônio  292216   
3387  29221700      Metildietanolamina e etildietanolamina  292217   
3388  29221800              2-(N,N-diisopropilamino)etanol  292218   

                                  sh6_mercadoria  \
2724                   Metanol (álcool metílico)   
2856           2,2-Oxidietanol (dietilenoglicol)   
3380                 Monoetanolamina e seus sais   
3381                   Dietanolamina e seus sais   
3382                  Trietanolamina e seus sais   
3383                  Trietanolamina e seus sais   
3385                              Trietanolamina   
3386  Perfluoroctanossulfonato de dietanolamônio   
3387      Metildietanolamina e etildietanolamina   
3388              2-(N,N-diisopropilamino)etanol   

                                            sh6_posicao  \
2724  Álcoois acíclicos e seus derivados halogenados...   
2856  Éteres, éteres-álcoois, éteres-fenóis, éteres-...   
3380           Compostos aminados de funções oxigenadas   
3381           Compostos aminados de funções oxigenadas   
3382           Compostos aminados de funções oxigenadas   
3383           Compostos aminados de funções oxigenadas   
3385           Compostos aminados de funções oxigenadas   
3386           Compostos aminados de funções oxigenadas   
3387           Compostos aminados de funções oxigenadas   
3388           Compostos aminados de funções oxigenadas   

                     sh6_capitulo  \
2724  Produtos químicos orgânicos   
2856  Produtos químicos orgânicos   
3380  Produtos químicos orgânicos   
3381  Produtos químicos orgânicos   
3382  Produtos químicos orgânicos   
3383  Produtos químicos orgânicos   
3385  Produtos químicos orgânicos   
3386  Produtos químicos orgânicos   
3387  Produtos químicos orgânicos   
3388  Produtos químicos orgânicos   

                                              sh6_secao   cuci  \
2724  Produtos das indústrias químicas ou indústrias...  51211   
2856  Produtos das indústrias químicas ou indústrias...  51617   
3380  Produtos das indústrias químicas ou indústrias...  51461   
3381  Produtos das indústrias químicas ou indústrias...  51461   
3382  Produtos das indústrias químicas ou indústrias...  51461   
3383  Produtos das indústrias químicas ou indústrias...  51461   
3385  Produtos das indústrias químicas ou indústrias...  51461   
3386  Produtos das indústrias químicas ou indústrias...  51461   
3387  Produtos das indústrias químicas ou indústrias...  51461   
3388  Produtos das indústrias químicas ou indústrias...  51461   

                                              cuci_item  \
2724                          Metanol (álcool metílico)   
2856  Éteres-álcoois, éteres-fenóis, éteres-álcoois-...   
3380  Amino-álcoois, éteres e ésteres (exceto os que...   
3381  Amino-álcoois, éteres e ésteres (exceto os que...   
3382  Amino-álcoois, éteres e ésteres (exceto os que...   
3383  Amino-álcoois, éteres e ésteres (exceto os que...   
3385  Amino-álcoois, éteres e ésteres (exceto os que...   
3386  Amino-álcoois, éteres e ésteres (exceto os que...   
3387  Amino-álcoois, éteres e ésteres (exceto os que...   
3388  Amino-álcoois, éteres e ésteres (exceto os que...   

                                          cuci_subgrupo  \
2724                     Álcoois monohídricos acíclicos   
2856  Éteres, peróxidos de álcoois, peróxidos de éte...   
3380              Compostos amino de funções oxigenadas

Filtro = ETANOL.

29051100	Metanol (álcool metílico)	290511	Metanol (álcool metílico)	Álcoois acíclicos e seus derivados halogenados...	Produtos químicos orgânicos	Produtos das indústrias químicas ou indústrias...	51211	Metanol (álcool metílico)	Álcoois monohídricos acíclicos	Álcoois, fenóis, fenóis-álcoois, e seus deriva...	Produtos químicos orgânicos	PRODUTOS QUIMICOS E RELACIONADOS, N.E.P.	240	Insumos industriais elaborados	Insumos industriais elaborados	BENS INTERMEDIÁRIOS (BI)	2011	Fabricação de produtos químicos básicos	Fabricação de produtos químicos básicos, ferti...	Fabricação de produtos químicos	Indústria de Transformação	PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI..

In [ ]:
filtro_comb_ncm = df.produto.str.contains('gasolina')
filtro_comb_sh = df.sh6_mercadoria.str.contains('gasolina')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
1864  26202100            Lamas de gasolina contendo chumbo, etc.  262021   
1913  27100029                                   Outras gasolinas  271000   
1936  27101159                                   Outras gasolinas  271011   
1946  27101259              Outras gasolinas, exceto para aviação  271012   
9934  84133010  Bombas para gasolina ou álcool, próprias para ...  841330   

                                         sh6_mercadoria  \
1864  Lamas de gasolina e de compostos antidetonante...   
1913  Naftas, gasolinas, querosenes, gasóleo, outros...   
1936  Óleos leves de petróleo ou de minerais betumin...   
1946                          Óleos leves e preparações   
9934  Bombas para combustíveis, lubrificantes ou líq...   

                                            sh6_posicao  \
1864  Cinzas e resíduos (exceto provenientes da fabr...   
1913  Óleos de petróleo ou de minerais betuminosos, ...   
1936  Óleos de petróleo ou de minerais betuminosos, ...   
1946  Óleos de petróleo ou de minerais betuminosos, ...   
9934  Bombas para líquidos, mesmo com dispositivo me...   

                                           sh6_capitulo  \
1864                        Minerios, escórias e cinzas   
1913  Combustíveis minerais, óleos minerais e produt...   
1936  Combustíveis minerais, óleos minerais e produt...   
1946  Combustíveis minerais, óleos minerais e produt...   
9934  Reatores nucleares, caldeiras, máquinas, apare...   

                                              sh6_secao  cuci  \
1864                                  Produtos minerais  2881   
1913                                  Produtos minerais  3346   
1936                                  Produtos minerais  3346   
1946                                  Produtos minerais  3346   
9934  Máquinas e aparelhos, material elétrico e suas...  7422   

                                              cuci_item  \
1864  Cinzas e resíduos (exceto os provenientes da f...   
1913  Óleos de petróleo ou de minerais betuminosos (...   
1936  Óleos de petróleo ou de minerais betuminosos (...   
1946  Óleos de petróleo ou de minerais betuminosos (...   
9934  Combustíveis, lubrificantes ou líquidos de arr...   

                                          cuci_subgrupo  \
1864  Cinzas e resíduos (exceto os provenientes da f...   
1913  Óleos de petróleo ou de minerais betuminosos (...   
1936  Óleos de petróleo ou de minerais betuminosos (...   
1946  Óleos de petróleo ou de minerais betuminosos (...   
9934  Combustíveis, lubrificantes ou líquidos de arr...   

                                             cuci_grupo  \
1864  Resíduos de metais de base não ferrosos e de s...   
1913  Óleos combustíveis de petróleo ou de minerais ...   
1936  Óleos combustíveis de petróleo ou de minerais ...   
1946  Óleos combustíveis de petróleo ou de minerais ...   
9934  Bombas para líquidos, elevadores de líquidos e...   

                                           cuci_divisao  \
1864                        Minérios metálicos e sucata   
1913  Petróleo, produtos petrolíferos e materiais re...   
1936  Petróleo, produtos petrolíferos e materiais re...   
1946  Petróleo, produtos petrolíferos e materiais re...   
9934  Máquinas em geral e equipamentos industriais, ...   

                                             cuci_secao  cgce  \
1864  MATERIAS EM BRUTO, NAO COMESTIVEIS, EXCETO COM...   230   
1913  COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...   420   
1936  COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...   420   
1946  COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...   420   
9934              MAQUINAS E EQUIPAMENTOS DE TRANSPORTE   280   

                                      cgce_economica_n3  \
1864                        Insumos industriais básicos   
1913  Gasolinas para automóvel (motor spirit) – indí...   
1936  Gasolinas para automóvel (motor spirit) – indí...   
1946  Gasolinas para automóvel (motor spirit)

In [ ]:
df.loc[filtro_comb_sh]

ncm                                            produto     sh6  \
1864  26202100            Lamas de gasolina contendo chumbo, etc.  262021   
1910  27100011                           Naftas para petroquímica  271000   
1911  27100019                                      Outras naftas  271000   
1912  27100021                               Gasolinas de aviação  271000   
1913  27100029                                   Outras gasolinas  271000   
1914  27100031                              Querosenes de aviação  271000   
1915  27100039                                  Outros querosenes  271000   
1916  27100041                              Gasóleo (óleo diesel)  271000   
1917  27100042                        Fuel-oil (óleo combustivel)  271000   
1918  27100049                          Outros óleos combustíveis  271000   
1919  27100051            Diisobutileno (mistura de alquilidenos)  271000   
1920  27100059                    Outras misturas de alquilidenos  271000   
1921  27100061                   Óleos lubrificantes sem aditivos  271000   
1922  27100062                   Óleos lubrificantes com aditivos  271000   
1923  27100091                                   Hexano comercial  271000   
1924  27100092                                   Aguarrás mineral  271000   
1925  27100093  Óleos minerais brancos (óleos de vaselina ou p...  271000   
1926  27100094             Líquidos para transmissões hidráulicas  271000   
1927  27100095                     Óleos para isolamento elétrico  271000   
1928  27100099  Outros óleos de petróleo, minerais betuminosos...  271000   

                                         sh6_mercadoria  \
1864  Lamas de gasolina e de compostos antidetonante...   
1910  Naftas, gasolinas, querosenes, gasóleo, outros...   
1911  Naftas, gasolinas, querosenes, gasóleo, outros...   
1912  Naftas, gasolinas, querosenes, gasóleo, outros...   
1913  Naftas, gasolinas, querosenes, gasóleo, outros...   
1914  Naftas, gasolinas, querosenes, gasóleo, outros...   
1915  Naftas, gasolinas, querosenes, gasóleo, outros...   
1916  Naftas, gasolinas, querosenes, gasóleo, outros...   
1917  Naftas, gasolinas, querosenes, gasóleo, outros...   
1918  Naftas, gasolinas, querosenes, gasóleo, outros...   
1919  Naftas, gasolinas, querosenes, gasóleo, outros...   
1920  Naftas, gasolinas, querosenes, gasóleo, outros...   
1921  Naftas, gasolinas, querosenes, gasóleo, outros...   
1922  Naftas, gasolinas, querosenes, gasóleo, outros...   
1923  Naftas, gasolinas, querosenes, gasóleo, outros...   
1924  Naftas, gasolinas, querosenes, gasóleo, outros...   
1925  Naftas, gasolinas, querosenes, gasóleo, outros...   
1926  Naftas, gasolinas, querosenes, gasóleo, outros...   
1927  Naftas, gasolinas, querosenes, gasóleo, outros...   
1928  Naftas, gasolinas, querosenes, gasóleo, outros...   

                                            sh6_posicao  \
1864  Cinzas e resíduos (exceto provenientes da fabr...   
1910  Óleos de petróleo ou de minerais betuminosos, ...   
1911  Óleos de petróleo ou de minerais betuminosos, ...   
1912  Óleos de petróleo ou de minerais betuminosos, ...   
1913  Óleos de petróleo ou de minerais betuminosos, ...   
1914  Óleos de petróleo ou de minerais betuminosos, ...   
1915  Óleos de petróleo ou de minerais betuminosos, ...   
1916  Óleos de petróleo ou de minerais betuminosos, ...   
1917  Óleos de petróleo ou de minerais betuminosos, ...   
1918  Óleos de petróleo ou de minerais betuminosos, ...   
1919  Óleos de petróleo ou de minerais betuminosos, ...   
1920  Óleos de petróleo ou de minerais betuminosos, ...   
1921  Óleos de petróleo ou de minerais betuminosos, ...   
1922  Óleos de petróleo ou de minerais betuminosos, ...   
1923  Óleos de petróleo ou de minerais betuminosos, ...   
1924  Óleos de petróleo ou de minerais betuminosos, ...   
1925  Óleos de petróleo ou de minerais betuminosos, ...   
1926  Óleos de petróleo ou de minerais betuminosos, ...   
1927  Óleos de petróleo ou de mi

FILTRO = GASOLINA, DIESEL
2710---- Gasóleo (óleo diesel)	271000
Óleos de petróleo ou de minerais betuminosos, ...	Combustíveis minerais, óleos minerais e produt...	Produtos minerais	3346	Óleos de petróleo ou de minerais betuminosos (...	Óleos de petróleo ou de minerais betuminosos (...	Óleos combustíveis de petróleo ou de minerais ...	Petróleo, produtos petrolíferos e materiais re...	COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...	421	Combustíveis e lubrificantes elaborados - exce...	Combustíveis e lubrificantes elaborados	COMBUSTÍVEIS E LUBRIFICANTES	1920	Fabricação de produtos petrolíferos refinados	Fabricação de produtos petrolíferos refinados	Fabricação de coque e produtos petrolíferos re...	Indústria de Transformação	PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI..

In [ ]:
filtro_comb_ncm = df.produto.str.contains('glp|GLP')
filtro_comb_sh = df.sh6_mercadoria.str.contains('glp|GLP')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
1969  27111910                   Gás liquefeito de petróleo (glp)  271119   
6392  39233010  Recipientes para gás liquefeito de petróleo (GLP)  392330   

                                         sh6_mercadoria  \
1969  Outros gases liquefeitos de hidrocarbonetos ga...   
6392  Garrafões, garrafas, frascos, artigos semelhan...   

                                            sh6_posicao  \
1969   Gás de petróleo e outros hidrocarbonetos gasosos   
6392  Artigos de transporte ou de embalagem, de plás...   

                                           sh6_capitulo  \
1969  Combustíveis minerais, óleos minerais e produt...   
6392                             Plásticos e suas obras   

                                          sh6_secao   cuci  \
1969                              Produtos minerais   3442   
6392  Plásticos e suas obras; Borracha e suas obras  89319   

                                              cuci_item  \
1969       Hidrocarbonetos gasosos, liquefeitos, n.e.p.   
6392  Artigos de transporte ou de embalagem, n.e.p.;...   

                                          cuci_subgrupo  \
1969        Outros hidrocarbonetos gasosos, liquefeitos   
6392  Artigos de transporte ou de embalagem, de plás...   

                                            cuci_grupo  \
1969  Gás de petróleo e outros hidrocarbonetos gasosos   
6392                       Outros artigos de plásticos   

                                cuci_divisao  \
1969             Gás, natural e manufaturado   
6392  Artigos manufaturados diversos, n.e.p.   

                                             cuci_secao  cgce  \
1969  COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...   421   
6392                                     OBRAS DIVERSAS   240   

                                      cgce_economica_n3  \
1969  Combustíveis e lubrificantes elaborados - exce...   
6392                     Insumos industriais elaborados   

                                      cgce_n2                       cgce_n1  \
1969  Combustíveis e lubrificantes elaborados  COMBUSTÍVEIS E LUBRIFICANTES   
6392           Insumos industriais elaborados      BENS INTERMEDIÁRIOS (BI)   

      isic                          isic_class_industrial  \
1969  1920  Fabricação de produtos petrolíferos refinados   
6392  2220               Fabricação de produtos plásticos   

                                         isic_grupo  \
1969  Fabricação de produtos petrolíferos refinados   
6392               Fabricação de produtos plásticos   

                                           isic_divisao  \
1969  Fabricação de coque e produtos petrolíferos re...   
6392     Fabricação de produtos de borracha e plásticos   

                      isic_secao  \
1969  Indústria de Transformação   
6392  Indústria de Transformação   

                                  siit_setor_industrial  
1969  PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI...  
6392  PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI...

In [ ]:
df.loc[filtro_comb_sh]

Empty DataFrame
Columns: [ncm, produto, sh6, sh6_mercadoria, sh6_posicao, sh6_capitulo, sh6_secao, cuci, cuci_item, cuci_subgrupo, cuci_grupo, cuci_divisao, cuci_secao, cgce, cgce_economica_n3, cgce_n2, cgce_n1, isic, isic_class_industrial, isic_grupo, isic_divisao, isic_secao, siit_setor_industrial]
Index: []

FILTRO = GLP
27111910	Gás liquefeito de petróleo (glp)	271119	Outros gases liquefeitos de hidrocarbonetos ga...	Gás de petróleo e outros hidrocarbonetos gasosos	Combustíveis minerais, óleos minerais e produt...	Produtos minerais	3442	Hidrocarbonetos gasosos, liquefeitos, n.e.p.	Outros hidrocarbonetos gasosos, liquefeitos	Gás de petróleo e outros hidrocarbonetos gasosos	Gás, natural e manufaturado	COMBUSTIVEIS MINERAIS, LUBRIFICANTES E MATERIA...	421	Combustíveis e lubrificantes elaborados - exce...	Combustíveis e lubrificantes elaborados	COMBUSTÍVEIS E LUBRIFICANTES	1920	Fabricação de produtos petrolíferos refinados	Fabricação de produtos petrolíferos refinados	Fabricação de coque e produtos petrolíferos re...	Indústria de Transformação	PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI...

In [ ]:
filtro_comb_ncm = df.produto.str.contains('gnv|GNV|Gás|gás|Gas/gas')
filtro_comb_sh = df.sh6_mercadoria.str.contains('gnv|GNV|Gás|gás|Gas/gas')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
962     8121000  Cerejas conservadas transitoriamente (por exem...   81210   
964     8129000  Outras frutas conservadas transitoriamente (po...   81290   
1891   27050000  Gás de hulha, gás de água, gás pobre (gás de a...  270500   
1964   27111100                             Gás natural liquefeito  271111   
1969   27111910                   Gás liquefeito de petróleo (glp)  271119   
1971   27112100                       Gás natural no estado gasoso  271121   
1973   27112990  Outros hidrocarbonetos gasosos e gás petróleo,...  271129   
6392   39233010  Recipientes para gás liquefeito de petróleo (GLP)  392330   
9221   73042110  Tubos de aços não ligados, sem costura, para p...  730421   
9222   73042190  Outros tubos de ferro/aço, sem costura, para p...  730421   
9223   73042200  Hastes de perfuração de aço inoxidável, dos ti...  730422   
9224   73042310  Outras hastes de perfuração de aço não ligado,...  730423   
9225   73042390  Outros tubos de perfuração, sem costura, de fe...  730423   
9226   73042400  Outros tubos, dos tipos utilizados na extração...  730424   
9255   73052000  Tubos para revestimento de poços, dos tipos ut...  730520   
9263   73062100  Tubos para revestimento de poços, de produção ...  730621   
9264   73062900  Outros tubos para revestimento de poços, de pr...  730629   
9354   73211100  Aparelhos para cozinhar e aquecedores de prato...  732111   
9358   73218100  Outros aquecedores, etc, de ferro/aço, a combu...  732181   
9506   75089010  Cilindros ocos de seção variável, obtidos por ...  750890   
9808   83071010  Tubos flexíveis de aço, dos tipos utilizados n...  830710   
9840   84051000  Geradores de gás de ar (gás pobre) ou de gás d...  840510   
9841   84059000  Partes de geradores de gás de ar/gás de água, ...  840590   
9915   84118100  Outras turbinas a gás, de potência não superio...  841181   
9916   84118200  Outras turbinas a gás, de potência superior a ...  841182   
9918   84119900                    Partes de outras turbinas a gás  841199   
10037  84191100  Aquecedores de água, de aquecimento instantâne...  841911   
10813  84682000  Outras máquinas e aparelhos a gás, para temper...  846820   
10818  84689090  Partes de outras máquinas e aparelhos para sol...  846890   
11114  84818031  Outras válvulas, dos tipos utilizados em equip...  848180   
11115  84818039  Outras válvulas dos tipos utilizados em equipa...  848180   
11879  85363010  Centelhador a gás, para uma tensão não superio...  853630   
11904  85372010  Subestações isoladas a gás (GIS - Gas-Insulate...  853720   
12180  85480010  Termopares dos tipos utilizados em dispositivo...  854800   
12185  85489010  Termopares dos tipos utilizados em dispositivo...  854890   
12824  90281010  Contadores de gás natural comprimido, eletrônicos  902810   
12825  90281011  Contadores de gás natural comprimido eletrônic...  902810   
12826  90281019  Outros contadores de gás natural comprimido, e...  902810   
13042  93040000  Outras armas (por exemplo, espingardas, carabi...  930400   
13044  93040090  Outras armas (por exemplo, espingardas, carabi...  930400   
13278  96131000       Isqueiros de bolso, a gás, não recarregáveis  961310   
13279  96132000           Isqueiros de bolso, a gás, recarregáveis  961320   

                                          sh6_mercadoria  \
962    Cerejas conservadas transitoriamente, mas impr...   
964    Outras frutas conservadas transitoriamente, ma...   
1891   Gás de hulha, gás de água, gás pobre e gases s...   
1964                             Gás natural, liquefeito   
1969   Outros gases liquefeitos de hidrocarbonetos ga...   
1971                        Gás natural no estado gasoso   
1973   Butanos, outros hidrocarbonetos e gás petróleo...   
6392   Garrafões, garrafas, frascos, artigos semelhan...   
9221                                       Tubos de aços   
9222                                       Tubos de aços 

In [ ]:
df.loc[filtro_comb_sh]

ncm                                            produto     sh6  \
1891   27050000  Gás de hulha, gás de água, gás pobre (gás de a...  270500   
1964   27111100                             Gás natural liquefeito  271111   
1971   27112100                       Gás natural no estado gasoso  271121   
1972   27112910                           Butanos no estado gasoso  271129   
1973   27112990  Outros hidrocarbonetos gasosos e gás petróleo,...  271129   
9223   73042200  Hastes de perfuração de aço inoxidável, dos ti...  730422   
9224   73042310  Outras hastes de perfuração de aço não ligado,...  730423   
9225   73042390  Outros tubos de perfuração, sem costura, de fe...  730423   
9226   73042400  Outros tubos, dos tipos utilizados na extração...  730424   
9227   73042910  Tubos de aço não ligado, sem costura, para rev...  730429   
9228   73042920  Tubos de aço inoxidável sem costura, para reve...  730429   
9229   73042931  Tubos de outras ligas de aço não revestidos, s...  730429   
9230   73042939  Outros tubos de ligas de aços, não revestidos,...  730429   
9231   73042990  Outros tubos de ferro fundido, ferro ou aço, s...  730429   
9255   73052000  Tubos para revestimento de poços, dos tipos ut...  730520   
9263   73062100  Tubos para revestimento de poços, de produção ...  730621   
9264   73062900  Outros tubos para revestimento de poços, de pr...  730629   
9354   73211100  Aparelhos para cozinhar e aquecedores de prato...  732111   
9358   73218100  Outros aquecedores, etc, de ferro/aço, a combu...  732181   
9840   84051000  Geradores de gás de ar (gás pobre) ou de gás d...  840510   
9841   84059000  Partes de geradores de gás de ar/gás de água, ...  840590   
9915   84118100  Outras turbinas a gás, de potência não superio...  841181   
9916   84118200  Outras turbinas a gás, de potência superior a ...  841182   
9918   84119900                    Partes de outras turbinas a gás  841199   
10037  84191100  Aquecedores de água, de aquecimento instantâne...  841911   
10038  84191200                        Aquecedores solares de água  841912   
10813  84682000  Outras máquinas e aparelhos a gás, para temper...  846820   
10816  84689010                  Partes de maçaricos de uso manual  846890   
10817  84689020  Partes de máquinas e aparelhos para soldar por...  846890   
10818  84689090  Partes de outras máquinas e aparelhos para sol...  846890   
13042  93040000  Outras armas (por exemplo, espingardas, carabi...  930400   
13043  93040010  Recipientes do tipo aerossol que contenham pro...  930400   
13044  93040090  Outras armas (por exemplo, espingardas, carabi...  930400   
13278  96131000       Isqueiros de bolso, a gás, não recarregáveis  961310   
13279  96132000           Isqueiros de bolso, a gás, recarregáveis  961320   

                                          sh6_mercadoria  \
1891   Gás de hulha, gás de água, gás pobre e gases s...   
1964                             Gás natural, liquefeito   
1971                        Gás natural no estado gasoso   
1972   Butanos, outros hidrocarbonetos e gás petróleo...   
1973   Butanos, outros hidrocarbonetos e gás petróleo...   
9223   Tubos de perfuração, sem costura, de aços inox...   
9224   Outros tubos de perfuração, sem costura, de fe...   
9225   Outros tubos de perfuração, sem costura, de fe...   
9226   Outros tubos, dos tipos utilizados na extração...   
9227   Outros tubos de revestimento de poços, de supr...   
9228   Outros tubos de revestimento de poços, de supr...   
9229   Outros tubos de revestimento de poços, de supr...   
9230   Outros tubos de revestimento de poços, de supr...   
9231   Outros tubos de revestimento de poços, de supr...   
9255   Tubos de ferro ou aço, soldados, de seção circ...   
9263   Tubos soldados, de aços inoxidáveis, de revest...   
9264   Outros tubos, de ferro ou aço, de revestimento...   
9354   Aparelhos para cozinhar e aquecedores de prato...   
9358   Aquecedores de ambientes (fogões de sala) e ca...   
984

27050000	Gás de hulha, gás de água, gás pobre (gás de a...	270500	Gás de hulha, gás de água, gás pobre e gases s...	Gás de hulha, gás de água, gás pobre (gás de a...

27111100	Gás natural liquefeito	271111	Gás natural, liquefeito	Gás de petróleo e outros hidrocarbonetos gasosos

27111910	Gás liquefeito de petróleo (glp)	271119	Outros gases liquefeitos de hidrocarbonetos ga...	Gás de petróleo e outros hidrocarbonetos gasosos

27112100	Gás natural no estado gasoso	271121	Gás natural no estado gasoso	Gás de petróleo e outros hidrocarbonetos gasosos

27112990	Outros hidrocarbonetos gasosos e gás petróleo,...	271129	Butanos, outros hidrocarbonetos e gás petróleo...	Gás de petróleo e outros hidrocarbonetos gasosos




In [ ]:
filtro_comb_ncm = df.produto.str.contains('diesel')
filtro_comb_sh = df.sh6_mercadoria.str.contains('diesel')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
1916   27100041                              Gasóleo (óleo diesel)  271000   
1951   27101921                              Gasóleo (óleo diesel)  271019   
6038   38260000  Biodiesel e suas misturas, que não contenham o...  382600   
9864   84081010  Motores diesel/semidiesel, para embarcação, ti...  840810   
9865   84081090  Outros motores diesel/semidiesel, para embarcação  840810   
...         ...                                                ...     ...   
12272  87042290  Outros veículos automóveis com motor diesel, c...  870422   
12273  87042310  Chassis com motor diesel e cabina, capacidade ...  870423   
12274  87042320  Veículos automóveis com motor diesel, caixa ba...  870423   
12275  87042330  Veículos automóveis frigoríficos com motor die...  870423   
12277  87042390  Outros veículos automóveis motor diesel, carga...  870423   

                                          sh6_mercadoria  \
1916   Naftas, gasolinas, querosenes, gasóleo, outros...   
1951   Outros óleos de petróleo ou de minerais betumi...   
6038   Biodiesel e suas misturas, com > 70% peso de p...   
9864   Motores de pistão, de ignição por compressão, ...   
9865   Motores de pistão, de ignição por compressão, ...   
...                                                  ...   
12272  Veículos automóveis para transporte de mercado...   
12273  Veículos automóveis para transporte de mercado...   
12274  Veículos automóveis para transporte de mercado...   
12275  Veículos automóveis para transporte de mercado...   
12277  Veículos automóveis para transporte de mercado...   

                                             sh6_posicao  \
1916   Óleos de petróleo ou de minerais betuminosos, ...   
1951   Óleos de petróleo ou de minerais betuminosos, ...   
6038   Biodiesel e suas misturas, que não contenham o...   
9864   Motores de pistão, de ignição por compressão (...   
9865   Motores de pistão, de ignição por compressão (...   
...                                                  ...   
12272  Veículos automóveis para transporte de mercado...   
12273  Veículos automóveis para transporte de mercado...   
12274  Veículos automóveis para transporte de mercado...   
12275  Veículos automóveis para transporte de mercado...   
12277  Veículos automóveis para transporte de mercado...   

                                            sh6_capitulo  \
1916   Combustíveis minerais, óleos minerais e produt...   
1951   Combustíveis minerais, óleos minerais e produt...   
6038           Produtos diversos das indústrias químicas   
9864   Reatores nucleares, caldeiras, máquinas, apare...   
9865   Reatores nucleares, caldeiras, máquinas, apare...   
...                                                  ...   
12272  Veículos automóveis, tratores, ciclos e outros...   
12273  Veículos automóveis, tratores, ciclos e outros...   
12274  Veículos automóveis, tratores, ciclos e outros...   
12275  Veículos automóveis, tratores, ciclos e outros...   
12277  Veículos automóveis, tratores, ciclos e outros...   

                                               sh6_secao   cuci  \
1916                                   Produtos minerais   3346   
1951                                   Produtos minerais   3346   
6038   Produtos das indústrias químicas ou indústrias...  59899   
9864   Máquinas e aparelhos, material elétrico e suas...  71333   
9865   Máquinas e aparelhos, material elétrico e suas...  71333   
...                                                  ...    ...   
12272                             Material de transporte  78219   
12273                             Material de transporte  78219   
12274                             Material de transporte  78219   
12275                             Material de transporte  78219   
12277                             Material de transporte  78219   

                                               cuci_item  \
1916   Óleos de petróleo ou de minerais betumin

In [ ]:
df.loc[filtro_comb_sh]

ncm                                            produto     sh6  \
6038   38260000  Biodiesel e suas misturas, que não contenham o...  382600   
9864   84081010  Motores diesel/semidiesel, para embarcação, ti...  840810   
9865   84081090  Outros motores diesel/semidiesel, para embarcação  840810   
9866   84082010  Motores diesel/semidiesel, para vículos do cap...  840820   
9867   84082020  Motores diesel/semidiesel, para veículos do ca...  840820   
9868   84082030  Motores diesel/semidiesel, para veículos do ca...  840820   
9869   84082090  Outros motores diesel/semidiesel, para veículo...  840820   
9870   84089010  Outros motores diesel, estacionários, potência...  840890   
9871   84089090                   Outros motores diesel/semidiesel  840890   
9885   84099911           Bielas para motores diesel ou semidiesel  840999   
9886   84099912  Blocos de cilindros, cabeçotes, etc, para moto...  840999   
9887   84099913        Injetores para motores diesel ou semidiesel  840999   
9888   84099914  Válvulas de admissão ou de escape, para motore...  840999   
9889   84099915  Coletores de admissão ou escape, para motores ...  840999   
9890   84099916  Anéis de segmento, para motores a diesel ou se...  840999   
9891   84099917  Guias de válvulas, para motores diesel ou semi...  840999   
9892   84099920  Pistões ou embolos, para motores diesel ou sem...  840999   
9893   84099921  Pistões/embolos, com diâmetro superior ou igua...  840999   
9894   84099929  Outros pistões ou embolos, para motores diesel...  840999   
9895   84099930  Camisas de cilindro, para motores diesel ou se...  840999   
9896   84099941  Bielas com peso superior ou igual a 30 kg, par...  840999   
9897   84099949      Outras bielas, para motores diesel/semidiesel  840999   
9898   84099951  Cabeçotes, com diâmetro superior ou igual a 20...  840999   
9899   84099959    Outros cabeçotes para motores diesel/semidiesel  840999   
9900   84099961  Injetores/bicos injetores, com diâmetro superi...  840999   
9901   84099969    Outros injetores para motores diesel/semidiesel  840999   
9902   84099971  Anéis de segmento, com diâmetro superior ou ig...  840999   
9903   84099979  Outros anéis de segmento, para motores diesel/...  840999   
9904   84099990    Outras partes para motores diesel ou semidiesel  840999   
9905   84099991  Camisas de cilindro soldadas a cabeçotes, com ...  840999   
9906   84099999     Outras partes para motores diesel e semidiesel  840999   
12190  86021000                       Locomotivas diesel-elétricas  860210   
12235  87022000  Veículos automóveis para transporte de dez pes...  870220   
12250  87033110  Automóveis com motor diesel, cm3 <= 1500, até ...  870331   
12251  87033190  Automóveis com motor diesel, cm3 <= 1500, supe...  870331   
12257  87035000  Outros veículos, equipados para propulsão, sim...  870350   
12259  87037000  Outros veículos, equipados para propulsão, sim...  870370   

                                          sh6_mercadoria  \
6038   Biodiesel e suas misturas, com > 70% peso de p...   
9864   Motores de pistão, de ignição por compressão, ...   
9865   Motores de pistão, de ignição por compressão, ...   
9866   Motores de pistão, de ignição por compressão, ...   
9867   Motores de pistão, de ignição por compressão, ...   
9868   Motores de pistão, de ignição por compressão, ...   
9869   Motores de pistão, de ignição por compressão, ...   
9870   Outros motores de pistão, de ignição por compr...   
9871   Outros motores de pistão, de ignição por compr...   
9885     Outras partes para motores diesel ou semidiesel   
9886     Outras partes para motores diesel ou semidiesel   
9887     Outras partes para motores diesel ou semidiesel   
9888     Outras partes para motores diesel ou semidiesel   
9889     Outras partes para motores diesel ou semidiesel   
9890     Outras partes para motores diesel ou semidiesel   
9891     Outras partes para motores diesel ou semidiesel   
9892     Outras partes para



FILTRO = DIESEL
38260000	Biodiesel e suas misturas, que não contenham o.. 

Biodiesel e suas misturas, que não contenham o...	Produtos diversos das indústrias químicas	Produtos das indústrias químicas ou indústrias...	59899	Outros produtos e preparações químicas	Outros produtos químicos e preparações	Outros produtos diversos das indústrias químicas	Materiais e produtos químicos, n.e.p.	PRODUTOS QUIMICOS E RELACIONADOS, N.E.P.	240	Insumos industriais elaborados	Insumos industriais elaborados	BENS INTERMEDIÁRIOS (BI)	2029	Fabricação de outros produtos químicos n.c	Fabricação de outros produtos químicos	Fabricação de produtos químicos	Indústria de Transformação	PRODUTOS DA INDUSTRIA DE TRANSFORMAÇÃO DE MEDI.

In [ ]:
filtro_comb_ncm = df.produto.str.contains('álcool|Álcool')
filtro_comb_sh = df.sh6_mercadoria.str.contains('álcool|Álcool')

In [ ]:
df.loc[filtro_comb_ncm]

ncm                                            produto     sh6  \
1544  20091100  Suco (sumo) de laranja, não fermentados, sem a...  200911   
1545  20091200  Suco (sumo) de laranja, não fermentados, sem a...  200912   
1546  20091900  Outros sucos de laranjas, não fermentados, sem...  200919   
1574  20099000  Misturas de sucos (sumos), não fermentados, se...  200990   
1619  22029100                                 Cerveja sem álcool  220291   
1620  22029900  Outras bebidas não-alcoólicas (exceto água, ce...  220299   
1624  22042100  Outros vinhos, mostos de uvas, fermentados, im...  220421   
1628  22042900  Outros vinhos, mostos de uvas, fermentação imp...  220429   
1638  22071000  Álcool etílico não desnaturado, com volume de ...  220710   
1639  22071010  Álcool etílico não desnaturado, com um teor al...  220710   
1640  22071090               Outro álcool etílico não desnaturado  220710   
1641  22072010  Álcool etílico desnaturado com qualquer teor a...  220720   
1642  22072011  Álcool etílico com um teor de água igual ou in...  220720   
1643  22072019                   Outro álcool etílico desnaturado  220720   
2724  29051100                          Metanol (álcool metílico)  290511   
2725  29051210                                   Álcool propílico  290512   
2726  29051220                                Álcool isopropílico  290512   
2727  29051300                     Butan-1-ol (álcool n-butílico)  290513   
2728  29051410            Álcool isobutílico (2-metil-1-propanol)  290514   
2729  29051420                    Álcool sec-butílico (2-butanol)  290514   
2730  29051430           Álcool ter-butílico (2-metil-2-propanol)  290514   
2731  29051500          Pentanol (álcool amílico) e seus isômeros  290515   
2732  29051600          Octanol (álcool octilico) e seus isômeros  290516   
2733  29051710                                     Álcool láurico  290517   
2734  29051720                                    Álcool cetílico  290517   
2735  29051730                                   Álcool esteárico  290517   
2742  29051929                        Outros álcoolatos metálicos  290519   
2747  29051995        3,3-Dimetilbutan-2-ol (álcool pinacolílico)  290519   
2748  29051996          Pentanol (álcool amílico) e seus isômeros  290519   
2754  29052910                                     Álcool alílico  290529   
2765  29054400                 D-glucitol (sorbitol) (poliálcool)  290544   
2781  29061940  Álcool fenchílico (1, 3, 3-trimetil-2-norborna...  290619   
2784  29062100                                   Álcool benzílico  290621   
2877  29094950                             Álcool fenoxibenzílico  290949   
2953  29144010  4-hidroxi-4-metilpentano-2-ona (diacetona álcool)  291440   
3148  29181990  Outros ácidos carboxilicos função álcool, anid...  291819   
3602  29269021                Álcool alfa-ciano-3-fenoxibenzílico  292690   
3608  29269029  Outros derivados ésteres do álcool alfa-ciano-...  292690   
3832  29321300   Álcool furfurílico e álcool tetraidrofurfurílico  293213   
3833  29321310                                 Álcool furfurílico  293213   
3834  29321320                        Álcool tetraidrofurfurílico  293213   
3970  29333959  Outros compostos heterocíclicos função álcool,...  293339   
4067  29335949  Outros compostos heterocíclicos ciclo pirimidi...  293359   
4397  29362111                       Vitamina A1 álcool (retinol)  293621   
4398  29362112                      Acetato de vitamina A1 álcool  293621   
4399  29362113                    Palmitato de vitamina a1 álcool  293621   
4400  29362119  Outros derivados da vitamina A1 álcool, não mi...  293621   
5893  38237010         Álcool esteárico (álcool graxo industrial)  382370   
5894  38237020           Álcool láurico (álcool graxo industrial)  382370   
5896  38237040          Álcool cetílico (álcool graxo industrial)  382370   
5904  38246000  Sorbitol, exceto o da subposição 2905.44 (poli...  382460   
5955  3

In [ ]:
df.loc[filtro_comb_sh]

ncm                                            produto     sh6  \
1619  22029100                                 Cerveja sem álcool  220291   
1620  22029900  Outras bebidas não-alcoólicas (exceto água, ce...  220299   
1624  22042100  Outros vinhos, mostos de uvas, fermentados, im...  220421   
1625  22042211  Vinhos em recipientes de capacidade não superi...  220422   
1626  22042219  Vinhos em recipientes de capacidade superior a...  220422   
1627  22042220  Mostos de uvas, em recipientes de capacidade s...  220422   
1628  22042900  Outros vinhos, mostos de uvas, fermentação imp...  220429   
1629  22042910  Vinhos em recipientes de capacidade superior a...  220429   
1630  22042911  Vinhos em recipientes de capacidade não superi...  220429   
1631  22042919  Vinhos em recipientes de capacidade superior a...  220429   
1632  22042920                                             Mostos  220429   
1638  22071000  Álcool etílico não desnaturado, com volume de ...  220710   
1639  22071010  Álcool etílico não desnaturado, com um teor al...  220710   
1640  22071090               Outro álcool etílico não desnaturado  220710   
1641  22072010  Álcool etílico desnaturado com qualquer teor a...  220720   
1642  22072011  Álcool etílico com um teor de água igual ou in...  220720   
1643  22072019                   Outro álcool etílico desnaturado  220720   
1644  22072020  Aguardente desnaturado com qualquer teor alcoó...  220720   
2724  29051100                          Metanol (álcool metílico)  290511   
2725  29051210                                   Álcool propílico  290512   
2726  29051220                                Álcool isopropílico  290512   
2727  29051300                     Butan-1-ol (álcool n-butílico)  290513   
2731  29051500          Pentanol (álcool amílico) e seus isômeros  290515   
2732  29051600          Octanol (álcool octilico) e seus isômeros  290516   
2733  29051710                                     Álcool láurico  290517   
2734  29051720                                    Álcool cetílico  290517   
2735  29051730                                   Álcool esteárico  290517   
2765  29054400                 D-glucitol (sorbitol) (poliálcool)  290544   
2784  29062100                                   Álcool benzílico  290621   
3140  29181910                                     Bromopropilato  291819   
3141  29181921                   Ursodiol (ácido ursodeoxicólico)  291819   
3142  29181922                             Ácido quenodeoxicólico  291819   
3143  29181929  Ácido biliar, seus outros sais, ésteres e deri...  291819   
3144  29181930                          Ácido 12-hidroxiesteárico  291819   
3145  29181941  Ácido benzílico (ácido 2, 2-difenil-2-hidroxia...  291819   
3146  29181942                            Sais do ácido benzílico  291819   
3147  29181943                         Ésteres do ácido benzílico  291819   
3148  29181990  Outros ácidos carboxilicos função álcool, anid...  291819   
3832  29321300   Álcool furfurílico e álcool tetraidrofurfurílico  293213   
3833  29321310                                 Álcool furfurílico  293213   
3834  29321320                        Álcool tetraidrofurfurílico  293213   
5904  38246000  Sorbitol, exceto o da subposição 2905.44 (poli...  382460   
6103  39053000             Álcool polivinílico, em forma primária  390530   

                                         sh6_mercadoria  \
1619                                 Cerveja sem álcool   
1620  Outras bebidas não-alcoólicas (exceto água, ce...   
1624  Outros vinhos; mostos de uvas, cuja fermentaçã...   
1625  Outros vinhos; mostos de uvas cuja fermentação...   
1626  Outros vinhos; mostos de uvas cuja fermentação...   
1627  Outros vinhos; mostos de uvas cuja fermentação...   
1628  Outros vinhos; mostos de uvas, cuja fermentaçã...   
1629  Outros vinhos; mostos de uvas, cuja fermentaçã...   
1630  Outros vinhos; mostos de uvas, cuja fermentaçã...   
1631  Outros vinhos; mostos de u

##lista de interrese

In [ ]:
ncm	      produto	          sh6	sh6_mercadoria	sh4_posicao	
27100029	Outras gasolinas	271000	Naftas, gasolinas, querosenes, gasóleo, outros...	Óleos de petróleo ou de minerais betuminosos, ...
27100041	Gasóleo (óleo diesel)	271000	Naftas, gasolinas, querosenes, gasóleo, outros...	Óleos de petróleo ou de minerais betuminosos, ...
27100042	Fuel-oil (óleo combustivel)	271000	Naftas, gasolinas, querosenes, gasóleo, outros...	Óleos de petróleo ou de minerais betuminosos, ...
27100049	Outros óleos combustíveis	271000	Naftas, gasolinas, querosenes, gasóleo, outros...	Óleos de petróleo ou de minerais betuminosos, ...
27101159	Outras gasolinas	271011	Óleos leves de petróleo ou de minerais betumin...	Óleos de petróleo ou de minerais betuminosos, ...
27101259	Outras gasolinas, exceto para aviação	271012	Óleos leves e preparações	Óleos de petróleo ou de minerais betuminosos, ...
27101921	Gasóleo (óleo diesel)	271019	Outros óleos de petróleo ou de minerais betumi...	Óleos de petróleo ou de minerais betuminosos, ...
27111100	Gás natural liquefeito	271111	Gás natural, liquefeito	Gás de petróleo e outros hidrocarbonetos gasosos
27111910	Gás liquefeito de petróleo (glp)	271119	Outros gases liquefeitos de hidrocarbonetos ga...	Gás de petróleo e outros hidrocarbonetos gasosos
27112100	Gás natural no estado gasoso	271121	Gás natural no estado gasoso	Gás de petróleo e outros hidrocarbonetos gasosos
27112990	Outros hidrocarbonetos gasosos e gás petróleo,...	271129	Butanos, outros hidrocarbonetos e gás petróleo...	Gás de petróleo e outros hidrocarbonetos gasosos
29051100  Metanol (álcool metílico) 290511 Metanol (álcool metílico) Álcoois acíclicos e seus derivados halogenados...
38260000	Biodiesel e suas misturas, que não contenham o...	382600	Biodiesel e suas misturas, com > 70% peso de p...	Biodiesel e suas misturas, que não contenham o...


##procurar esse códigos na bases completas de importação e exportação

In [ ]:
sh6 = [271000, 271011, 271012,271019,271111,271119,271121,271129,290511,382600]
ncm = [27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000]
#o sh4 é inclui algumas variações
sh4 = [2710, 2711, 2905, 3826]

In [ ]:
#ver para esses ncm qual é o cuci!

#4 - analise spark

feita em outro colab
<a href="https://colab.research.google.com/drive/1lqZ8jtAtEbTtEfDtkLD4EBGSjWkU9mM-#scrollTo=326clQ-PKkj7">Comex-pyspark</a>

na VM-colab

In [ ]:
#mortar o dataframe no pyspark, usando o esquema
def montar_df(caminho, formato):
  df = ( spark.read.format(formato)
                 .option('header', 'true')
                 .option('inferschema', 'true')
                 .option('delimiter', ',')
                 .load(caminho))
  return df


In [ ]:
#chamar a função para criar a base com o esquema
# dfpais = montar_df(path_pais, 'csv')

In [ ]:
# dfip = montar_df(path_ip, 'parquet')

In [ ]:
df_pais
dfpais = spark.createDataFrame(df_pais)

In [ ]:
dfpais.describe().show()

+-------+-----------------+----------+
|summary|          CO_PAIS|   NO_PAIS|
+-------+-----------------+----------+
|  count|              281|       281|
|   mean|449.4697508896797|      null|
| stddev| 266.870822101005|      null|
|    min|                0|A Designar|
|    max|              999|     Índia|
+-------+-----------------+----------+



In [ ]:
dfim = spark.createDAtaFrame(df_im)

In [ ]:
dfim.show()

base importação por produto.

In [ ]:
#covertar a de pandas para pyspark
dfip = spark.createDataFrame(df_ip)

In [ ]:
#pegando direto do bucket em spark
dfip = ( spark.read.format('parquet')
                 .option('header', 'true')
                 .option('inferschema', 'true')
                 .option('delimiter', ',')
                 .load(path_ip))

demorou 19min

In [ ]:
#estorou o tamanho da memória.
dfip.show()

In [ ]:
dfip.printSchema()

In [ ]:
dfip.describe().show()

In [ ]:
dfip.summary().show()

In [ ]:
#os 10 produtos importados com maior valor em dolares no 10 anos.
dfip.select(F.col('produto')).orderBy(F.col('valor_dolar').desc()).show(10)

In [ ]:
#agrupando por ano
dfip.select(F.col('produto')).groupBy(F.col('ano')).orderBy(F.col('valor_dolar').desc()).show()
#faz o que quero?

In [ ]:
#os 10 produtos importados com maior volume no 10 anos.
dfip.select(F.col('produto')).orderBy(F.col('peso_liquido').desc()).show(10)

In [ ]:
#agupando por ano
dfip.select(F.col('produto')).groupBy(F.col('ano')).orderBy(F.col('peso_liquido').desc()).show()

In [ ]:
#criar coluna com o valor das importação por volume transportado
dfip = dfip.withColumn('dolar_por_vol', F.round(F.col('valor_dolar')/F.col('peso_liquido'), 2))

In [ ]:
#os 10 produtos importados com maior valor por volume.
dfip.select(F.col('mercadoria')).orderBy(F.col('dolar_por_vol').desc()).show(10)

#Big Query

##select usado no BQ na importacao-ncm

In [ ]:
SELECT * FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` LIMIT 1000;

#as 10 maiores importação de produtos em 10 anos pelo valor (unica nota)
SELECT produto, valor_dolar FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
ORDER BY valor_dolar DESC LIMIT 10;

#em 10 anos os 10 maiores gastos em produtos
SELECT produto, sum(valor_dolar) as valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY produto ORDER BY sum(valor_dolar) DESC LIMIT 10;

#no ano de 2022, os 10 protudos importados com maior valor gasto nesses produtos
SELECT produto, sum(valor_dolar) AS valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE ano=2022 GROUP BY produto ORDER BY sum(valor_dolar) DESC LIMIT 10;

#as 10 maiores importação de produtos em 10 anos pelo volume em único produto num mês e ano
SELECT distinct(produto), peso_liquido FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
ORDER BY peso_liquido DESC LIMIT 10;

#em 10 anos os 10 produtos com maior volume importado
SELECT produto, sum(peso_liquido) as volume_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY produto ORDER BY sum(peso_liquido) DESC LIMIT 10;

#paises
#10 paises do qual há mais importados de em 10 anos em valor
SELECT p.pais, sum(i.valor_dolar) AS valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais=p.cod_pais
GROUP BY p.pais ORDER BY sum(i.valor_dolar) DESC LIMIT 10;

#10 paises do qual há mais importados de em 10 anos em volume
SELECT p.pais, sum(i.peso_liquido) AS volume_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais=p.cod_pais
GROUP BY p.pais ORDER BY sum(i.peso_liquido) DESC LIMIT 10;

#10 paises do mais foram importados em valor de produtos no ano de 2022
SELECT p.pais, sum(i.valor_dolar) AS valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais=p.cod_pais
WHERE i.ano=2022 GROUP BY p.pais ORDER BY sum(i.valor_dolar) DESC LIMIT 10;

#10 paises do mais foram importados em volume de produtos no ano de 2022
SELECT p.pais, sum(i.peso_liquido) AS valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais=p.cod_pais
WHERE i.ano=2022 GROUP BY p.pais ORDER BY sum(i.peso_liquido) DESC LIMIT 10;

#os 50 maiores produtos valor por volume (tipo dolar/metro cubico) dos produtos nos 10 anos.
#conferir qual é a unidade de volume usada!
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, (sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE peso_liquido !=0 GROUP BY produto ORDER BY dolar_por_volume DESC LIMIT 50;

#os 50 maiores produtos valor por volume dos produtos no ano de 2022
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, (sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE ano=2020 AND peso_liquido !=0
GROUP BY produto ORDER BY dolar_por_volume DESC LIMIT 50;

#as via de transporte com de acordo com o volume importado
SELECT meio_transporte, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY meio_transporte ORDER BY volume_total DESC;

#as via de transporte com de acordo com o volume importado no ano de 2020
SELECT meio_transporte, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE ano=2021
GROUP BY meio_transporte ORDER BY volume_total DESC;

#as via de transporte com de acordo com o valor importado
SELECT meio_transporte, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY meio_transporte ORDER BY valor_total DESC;

#meses e anos ordenado pelo volume total importado
SELECT ano, mes, sum(valor_dolar) as valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY ano, mes ORDER BY valor_total DESC;

#ano com maior valor de importação
SELECT ano, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY ano ORDER BY valor_total DESC;

#ano com maior volume de importação
SELECT ano, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY ano ORDER BY volume_total DESC;

#mes que ocorre mais importação ordenado pelo volume total importado
SELECT mes, sum(valor_dolar) as valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY mes ORDER BY valor_total DESC;



#filtro com os produtos que estão na base de combustívies
SELECT * FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000) LIMIT 1000;

#quantas entradas tem o filtro com produtos da base combustivel
SELECT count(*) FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000);

#quanto foi importado desdes produtos em valor e volume nos 10 anos
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000)
GROUP BY produto;

#acrescentando o valor por volume desses produtos nos 10 anos
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, (sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000)
GROUP BY produto ORDER BY dolar_por_volume DESC;

#acrescentando o valor por volume desses produtos no ano de 2022
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, (sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000)
AND ano=2020 GROUP BY produto ORDER BY dolar_por_volume DESC;


##group by usado na importação ncm

In [ ]:
#testando a sintaxe do inner join
SELECT im.produto, c.siit_setor_industrial 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm LIMIT 1000;

#de acordo com o SIIT
#valor total gasto em importação no 10 anos por setor industrial
SELECT c.siit_setor_industrial, SUM(im.valor_dolar) AS valor_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total;

#valor total gasto em importação no 10 anos em 
SELECT c.siit_setor_industrial, SUM(im.peso_liquido) AS volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY volume_total;

#juntando as duas queyries anterior
#valor total gasto em importação e o volume no 10 anos em relação a cada setor industrial
SELECT c.siit_setor_industrial, SUM(im.valor_dolar) AS valor_total, SUM(im.peso_liquido) AS volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1;

#valor total gasto em importação e o volume em relação a cada setor industrial em 2022
SELECT c.siit_setor_industrial, SUM(im.valor_dolar) AS valor_total, SUM(im.peso_liquido) AS volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
WHERE ano=2022 GROUP BY 1 ORDER BY valor_total;

#calcular percentual (todos os anos da base) valor total de importação
SELECT SUM(valor_dolar) AS valor_total FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`;
#2169120802018 dolares = 2 tri 169 bi 120 milhões de dolares

#média do valor de importação por mes-protudo
SELECT AVG(valor_dolar) AS media_valor FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`;
#106384.478 dolares por produto e mes

#média do volume de importação por mes-protudo
SELECT AVG(peso_liquido) AS media_volume FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`;
#82602.9 kg-l por produto e mes

#em única query ver a soma e média do valor e volume
SELECT SUM(valor_dolar) AS soma_total, AVG(valor_dolar) AS media_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`;
#1684227798719 volume total

#percentual do valor e de volume de importação de cada setor industrial
SELECT c.siit_setor_industrial, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY porcento_valor DESC;

#valor e percentual gasto em importação por setor industrial nos 11 anos
SELECT c.siit_setor_industrial, 
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY porcento_volume DESC;

#o valor e volume total no ano de 2022
SELECT SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`
WHERE ano=2022;
#valor total em 2022(250808584820) e volume total em (158139630507)

#valor e percentual gasto em importação por setor industrial no ano de 2022
SELECT c.siit_setor_industrial, 
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(250808584820) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(158139630507) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm WHERE ano=2022
GROUP BY 1 ORDER BY porcento_volume DESC;

#o valor e volume total em cada ano
SELECT ano, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`
GROUP BY ano ORDER BY ano;

#media e total de importação por valor e volume em cada mês
SELECT mes, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`
GROUP BY mes ORDER BY valor_total;

#no ano de 2022, o valor total, a média e a porcentagem no ano do valor e volume importado
SELECT mes, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
SUM(valor_dolar)*100/(250808584820) AS percentual_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume, 
SUM(peso_liquido)*100/(158139630507) AS percentual_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`
where ano =2022 GROUP BY mes ORDER BY percentual_valor DESC;

#salvar a tabela com o valor agrupado por ano para fazer a porcentagem em cada ano
CREATE OR REPLACE TABLE comercio_brasil.imp_ano AS (
  SELECT ano, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
  SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
  FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm`
  GROUP BY ano ORDER BY ano
);


#pela via de transporte, agora com percentual
#percentual do usa das via de transporte pelo o valor e  volume importado
SELECT meio_transporte, sum(valor_dolar)*100/(2169120802018) AS percentual_valor_via, 
sum(peso_liquido)*100/(1684227798719) AS percentual_volume_via
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
GROUP BY meio_transporte ORDER BY percentual_volume_via DESC;

#resultado esquisito no volume postal, olhar a contagem 
SELECT SUM(peso_liquido) AS volume_total, COUNT(peso_liquido) AS num_casos,
sum(peso_liquido)/(1684227798719) AS percentagem
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE meio_transporte = 'POSTAL';
#valor pequeno, está em notação cinetifica

#porcetual do uso das vias em importação em 2022 
#valor total em 2022(250808584820) e volume total em (158139630507)
SELECT meio_transporte, 
sum(valor_dolar) AS valor_total, sum(valor_dolar)*100/(250808584820) AS percentual_valor_via, 
sum(peso_liquido) AS volume_total, sum(peso_liquido)*100/(158139630507) AS percentual_volume_via
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` 
WHERE ano =2022 GROUP BY meio_transporte ORDER BY percentual_volume_via DESC;


#de acordo com as GCCE - Grandes Categorias Ecomonicas
#valor total e volume total importado em cada categoria do nível 1 (5 categorias)
SELECT c.cgce_n1, 
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada categoria do nível 2 (13 categorias)- mais interresante para gráfico
SELECT c.cgce_n2, 
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada categoria do nível 2 no ano de 2022
SELECT c.cgce_n2, 
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(250808584820) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(158139630507) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm WHERE ano=2022
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada categoria do nível 3 (19 categorias)
SELECT c.cgce_economica_n3,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#de acordo com o ISIC - classificação internacional das industrias
#valor total e volume total importado em cada seção do ISIC (4 sessões) - usar as sessões como filtros
SELECT c.isic_secao,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#100 produtos mais importados da Indústria de Transformação (filtro)
SELECT i.produto, SUM(i.valor_dolar) AS valor_total, AVG(i.valor_dolar) AS media_valor, 
SUM(i.peso_liquido) AS volume_total, AVG(i.peso_liquido) AS media_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
WHERE c.isic_secao = 'Indústria de Transformação'
GROUP BY i.produto ORDER BY valor_total DESC LIMIT 100;

#os 50 produtos mais importados da Indústria de Transformação em 2022
SELECT i.produto, SUM(i.valor_dolar) AS valor_total, AVG(i.valor_dolar) AS media_valor, 
SUM(i.peso_liquido) AS volume_total, AVG(i.peso_liquido) AS media_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
WHERE c.isic_secao = 'Indústria de Transformação' AND i.ano=2022
GROUP BY i.produto ORDER BY valor_total DESC LIMIT 50;

#valor total e volume total importado em cada seção do ISIC (39 divisões)
SELECT c.isic_divisao,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada grupo do ISIC (94 grupos)
SELECT c.isic_grupo,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada classificação do ISIC (172 classificações)
SELECT c.isic_class_industrial,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#de acordo com o CUCI - 
#valor total e volume total importado em cada seção do CUCI (10 secões) 
SELECT c.cuci_secao,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada divisão do CUCI (66 divisão) - lista interresante
SELECT c.cuci_divisao,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada divisão do CUCI no ano de 2022 - só foram 65 divisões diferentes.
SELECT c.cuci_divisao,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(250808584820) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(158139630507) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm WHERE im.ano=2022
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada grupo do CUCI (302 grupos) - lista mais detalhada
SELECT c.cuci_grupo,
SUM(im.valor_dolar) AS valor_total, SUM(im.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(im.peso_liquido) AS volume_total, SUM(im.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#ver a classificação CUCI para os produtos na base combustivies
SELECT distinct(im.produto), c.cuci_item, c.cuci_subgrupo, c.cuci_grupo, c.cuci_divisao, c.cuci_secao
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
WHERE mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000)
ORDER BY c.cuci_subgrupo;


#de acordo com o SH - sistema harmonizado 
#valor total e volume total importado em cada secão do SH6 (21 secões) 
SELECT c.sh6_secao,
SUM(i.valor_dolar) AS valor_total, SUM(i.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(i.peso_liquido) AS volume_total, SUM(i.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada capitulos do SH6 ou (SH2) (96 capitulos) -lista compreensiva dos protudos
SELECT c.sh6_capitulo,
SUM(i.valor_dolar) AS valor_total, SUM(i.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(i.peso_liquido) AS volume_total, SUM(i.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC;

#valor total e volume total importado em cada posições do SH6 dentro da cada capitulo ou (SH4), limitado pelo 100 com maior valor
SELECT c.sh6_posicao, 
SUM(i.valor_dolar) AS valor_total, SUM(i.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(i.peso_liquido) AS volume_total, SUM(i.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
GROUP BY 1 ORDER BY valor_total DESC LIMIT 100;

#valor total e volume total importado em cada posições do SH6 dentro da cada capitulo ou (SH4), limitado pelo 100 com maior volume
SELECT c.sh6_posicao,
SUM(i.valor_dolar) AS valor_total, SUM(i.valor_dolar)*100/(2169120802018) AS porcento_valor, 
SUM(i.peso_liquido) AS volume_total, SUM(i.peso_liquido)*100/(1684227798719) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm 
GROUP BY 1 ORDER BY volume_total DESC LIMIT 100;
#15° lugar - milho, 8 - trigo

#valor total e volume total importado em cada posições do SH6 dentro da cada capitulo ou (SH4), 
#limitado pelo 100 com maior volume, no ano de 2022
SELECT c.sh6_posicao,
SUM(i.valor_dolar) AS valor_total, SUM(i.valor_dolar)*100/(250808584820) AS porcento_valor, 
SUM(i.peso_liquido) AS volume_total, SUM(i.peso_liquido)*100/(158139630507) AS porcento_volume
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON i.mercadoria=c.ncm  WHERE i.ano=2022
GROUP BY 1 ORDER BY volume_total DESC LIMIT 100;


##slq usado em combustívies

In [ ]:
# 10 MAIORES PREÇOS, SELECIONAR PRODUTO E ANO: gasolina comum no ano de 2022
SELECT data_final as Data_levantamento, estado as Estado, municipio as Municipio, preco_medio_revenda as Preco_medio
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
WHERE produto = 'GASOLINA COMUM' AND data_final >= '2022-01-01 00:00:00' and data_final < '2023-01-01 00:00:00'
ORDER BY preco_medio_revenda DESC LIMIT 10;

# 10 MENORES PREÇOS, SELECIONAR PRODUTO E ANO: gasolina comun no ano de 2022
SELECT data_final as Data_levantamento, estado as Estado, municipio as Municipio, preco_medio_revenda as Preco_medio
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
WHERE produto = 'GASOLINA COMUM' AND data_final >= '2022-01-01 00:00:00' and data_final < '2023-01-01 00:00:00'
ORDER BY preco_medio_revenda ASC LIMIT 10;

#Os estados mais pesquisados, mais representados
SELECT estado, COUNT(*) AS num_registros, SUM(num_postos_pesquisados) AS num_postos_pesquisados
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022
GROUP BY 1 ORDER BY num_registros DESC;

#Preço minimo, médio e máximo por estado, SELECIONAR PRODUTO E ANO: gasolina comun no ano de 2022
SELECT estado, MIN(preco_medio_revenda) AS menor_preco, AVG(preco_medio_revenda) AS preco_medio, MAX(preco_medio_revenda) AS maior_preco
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022
WHERE produto = 'GASOLINA COMUM' AND data_final >= '2022-01-01 00:00:00' and data_final < '2023-01-01 00:00:00'
GROUP BY 1 ORDER BY preco_medio DESC;

#Preço minimo e máximo por ano, SELECIONAR PRODUTO E ANO: gasolina comun
SELECT extract(year FROM data_final) AS ano, MIN(preco_medio_revenda) AS menor_preco, MAX(preco_medio_revenda) AS maior_preco
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022
WHERE produto = 'GASOLINA COMUM' GROUP BY ano ORDER BY ano DESC;

#Preço máximo por estado por ano, SELECIONAR PRODUTO: gasolina comun
SELECT extract(year FROM data_final) AS ano, estado, MAX(preco_medio_revenda) AS preco_maximo
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
WHERE produto = 'GASOLINA COMUM' GROUP BY ano, estado ORDER BY ano DESC, preco_maximo DESC;

#Preço mínimo, médio e máximo por ano e regiao dos protudos
SELECT extract(year FROM data_final) AS ano, produto, regiao, 
MIN(preco_medio_revenda) AS preco_minimo, AVG(preco_medio_revenda) AS preco_medio,MAX(preco_medio_revenda) AS preco_maximo
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
GROUP BY ano, produto, regiao ORDER BY ano DESC, preco_medio;

#Preço minimo e máximo por ano de todos os produtos
SELECT extract(year FROM data_final) AS ano, produto, MIN(preco_medio_revenda) AS menor_preco, MAX(preco_medio_revenda) AS maior_preco
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022
GROUP BY ano, produto ORDER BY ano DESC, menor_preco;

#Preço médio anual por produto
SELECT produto, extract(year FROM data_final) AS ano, AVG(preco_medio_revenda) AS preco_medio_anual
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022
GROUP BY produto, ano;

#Preço médio mensal por produto
SELECT produto, extract(year FROM data_final) AS ano, extract(month FROM data_final) AS mes, AVG(preco_medio_revenda) AS preco_medio_mensal
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
GROUP BY produto, ano, mes ORDER BY ano DESC;

#sobre quantidade vendida
#Volume vendido por ano dos produto
SELECT ano, produto, SUM(qtde_vendas) AS litros_vendidos 
FROM `bc26-ed7-projeto-final.comercio_brasil.volume_preco_combustiveis_mensal_2013_2022`
GROUP BY produto, ano ORDER BY ano DESC, litros_vendidos DESC;

#Volume vendido por mes dos produtos nos postos pesquisados
SELECT produto, ano, mes, SUM(qtde_vendas) AS litros_vendidos 
FROM `bc26-ed7-projeto-final.comercio_brasil.volume_preco_combustiveis_mensal_2013_2022`
GROUP BY ano, mes, produto ORDER BY ano DESC, produto, litros_vendidos DESC;

#Volume vendido por ano dos produto por estado, junto com o volume médio vendido por mes
SELECT ano, produto, estado, SUM(qtde_vendas) AS litros_vendidos, AVG(qtde_vendas) AS volume_medio_mensal 
FROM `bc26-ed7-projeto-final.comercio_brasil.volume_preco_combustiveis_mensal_2013_2022`
GROUP BY produto, ano, estado ORDER BY ano DESC, produto, litros_vendidos DESC;


##query enviar ao looker

In [ ]:
#Filtro com as tabelas de exportação e  importação e combustívies para o looker

#colunas da base de exportação por municpipio - 29422
SELECT ano, mes, SH4, cod_pais, estado, municipio, valor_dolar, peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_mun`
WHERE SH4=2710 or SH4=2711 or SH4=3826;

#colunas da base de importação por municipio - 42685
SELECT ano, mes, SH4,descricoes__sistema_harmonizado, cod_pais, estado, municipio, valor_dolar, peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_mun`
WHERE SH4=2710 or SH4=2711 or SH4=3826;


#colunas de classificação, resulta em 8 produtos
Select ncm, produto, sh6_mercadoria
FROM`bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes`
WHERE ncm =27100029 or ncm =27100041 or ncm =27100042 or ncm =27101259 or ncm =27111100 or ncm =27111910 or ncm =27112100 or ncm = 38260000;

##queries para exportar para o looker
#tabela de exportação com o filtro
CREATE OR REPLACE TABLE comercio_brasil.exp_prod_comb AS (SELECT e.ano, e.mes, c.produto, p.pais, e.estado, e.meio_transporte, e.valor_dolar, e.peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` AS e
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON e.cod_mercadoria = c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON e.cod_pais = p.cod_pais
WHERE c.ncm =27100029 or c.ncm =27100041 or c.ncm =27100042 or c.ncm =27101259 or c.ncm =27111100 or c.ncm =27111910 or c.ncm =27112100 or c.ncm = 38260000);

#tabela de exportação com o filtro
CREATE OR REPLACE TABLE comercio_brasil.imp_prod_comb AS (SELECT i.ano, i.mes, c.produto, p.pais, i.estado, i.meio_transporte, i.valor_dolar, i.peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON i.mercadoria = c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais = p.cod_pais
WHERE ano !=2012 AND
c.ncm =27100029 or c.ncm =27100041 or c.ncm =27100042 or c.ncm =27101259 or c.ncm =27111100 or c.ncm =27111910 or c.ncm =27112100 or c.ncm = 38260000);

#tabela de combustíveis
SELECT data_inicial, data_final, produto, preco_medio_revenda, regiao, estado, municipio, num_postos_pesquisados, unidade_medida FROM `bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022`;



#colunas escolhidas para ir para o looker
Select ncm, produto, sh6_mercadoria, sh6_capitulo, sh6_secao, cuci_divisao, cuci_secao, cgce_n2, cgce_n1, isic_secao, siit_setor_industrial
FROM`bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes`;

#usar apenas por produto para enviar para o looker
#colunas da base de exportação por produto - 12 084 296
SELECT ano, mes, cod_mercadoria, mercadoria, cod_pais, estado, meio_transporte, valor_dolar, peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm`;

#colunas da base de importação por produto - 18 560 388
SELECT ano, mes, mercadoria, produto, cod_pais, estado, meio_transporte, valor_dolar, peso_liquido
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` WHERE ano !=2012;


#combinar exportação por produto com classificação - 12 071 288
CREATE OR REPLACE TABLE comercio_brasil.class_imp_prod AS (SELECT e.ano, e.mes, mercadoria, p.pais, e.estado, e.meio_transporte, e.valor_dolar, e.peso_liquido,
c.sh6_capitulo, c.sh6_secao, c.cuci_divisao, c.cuci_secao, c.cgce_n2, c.isic_secao, c.siit_setor_industrial
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` AS e
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON e.cod_mercadoria = c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON e.cod_pais = p.cod_pais);

#combinar importação por produto com classificação - 18 526 543
CREATE OR REPLACE TABLE comercio_brasil.class_exp_prod AS (SELECT i.ano, i.mes, i.produto, p.pais, i.estado, i.meio_transporte, i.valor_dolar, i.peso_liquido,
c.sh6_capitulo, c.sh6_secao, c.cuci_divisao, c.cuci_secao, c.cgce_n2, c.isic_secao, c.siit_setor_industrial
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON i.mercadoria = c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais = p.cod_pais WHERE i.ano !=2012);


#contar as linhas
SELECT count(*)
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON i.mercadoria=c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais = p.cod_pais WHERE i.ano !=2012;

Select sh6_mercadoria, produto
FROM`bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` limit 50;




#query com exportação
#relação entre o meio de transporte o estado que exporta ordenado pelo valor total
SELECT meio_transporte, estado, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY meio_transporte ,valor_total DESC;

#relação entre o meio de transporte o estado que exporta ordenado pelo volume total
SELECT meio_transporte, estado, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY meio_transporte ,volume_total DESC;
#a ordem dos estados muda em alguns meios

#uso de cada meio de transporte por ano ordenado por valor
SELECT ano, meio_transporte, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY ano DESC,valor_total DESC;

#uso de cada meio de transporte por ano ordenado por volume
SELECT ano, meio_transporte, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY ano DESC,volume_total DESC;

#uso de cada meio de transporte  ordenado por valor
SELECT meio_transporte, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1 ORDER BY valor_total DESC;

#uso de cada meio de transporte ordenado por volume
SELECT meio_transporte, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1 ORDER BY volume_total DESC;




#acrescentando o valor por volume desses produtos nos 10 anos
SELECT mercadoria, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, (sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm`
WHERE cod_mercadoria in (27100029, 27100041,27100042,27100049,27101159,27101259,27101921,27111100,27111910,27112100,27112990,29051100 ,38260000)
GROUP BY mercadoria ORDER BY dolar_por_volume DESC LIMIT 10;

##querys selecionadas para a documentação

In [ ]:
#combinar importação por produto com classificação, selecionar colunas para o looker
CREATE OR REPLACE TABLE looker.imp_prod AS (SELECT i.ano, i.mes, i.produto, p.pais, i.estado, i.meio_transporte, 
i.data, i.valor_dolar AS valor_importado, i.peso_liquido AS volume_importado,
c.sh6_capitulo, c.sh6_secao, c.cuci_divisao, c.cuci_secao, c.cgce_n2, c.isic_secao
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2013-2022_tratada_ncm` AS i
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c ON i.mercadoria = c.ncm
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON i.cod_pais = p.cod_pais);

#criar a tabela com o filtro para combustiveis para exportação, para combinar as análises e enviar ao looker 
CREATE OR REPLACE TABLE looker.exp_combustivel AS (SELECT e.ano, e.mes, e.mercadoria AS produto, p.pais, e.estado, e.meio_transporte, e.data, e.valor_dolar AS valor_exportado, e.peso_liquido AS volume_exportado
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` AS e
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.nome_pais` AS p ON e.cod_pais = p.cod_pais
WHERE e.cod_mercadoria = 27090010 or e.cod_mercadoria =27101922 or e.cod_mercadoria =99980101 or e.cod_mercadoria =99981002 or e.cod_mercadoria =27101259 or e.cod_mercadoria =27101921 or e.cod_mercadoria =27131100 or e.cod_mercadoria =27131200 or 
e.cod_mercadoria =27111100 or e.cod_mercadoria = 27101929 or e.cod_mercadoria =39111029 or e.cod_mercadoria =27111910);

#relação entre o meio de transporte o estado que exporta ordenado pelo volume total
SELECT meio_transporte, estado, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY meio_transporte ,volume_total DESC;

# 10 MENORES PREÇOS, SELECIONAR PRODUTO E ANO: gasolina comun no ano de 2022
SELECT data_final as Data_levantamento, estado as Estado, municipio as Municipio, preco_medio_revenda as Preco_medio
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
WHERE produto = 'GASOLINA COMUM' AND data_final >= '2022-01-01 00:00:00' and data_final < '2023-01-01 00:00:00'
ORDER BY preco_medio_revenda ASC LIMIT 10;

#Preço mínimo, médio e máximo por ano e regiao dos protudos
SELECT extract(year FROM data_final) AS ano, produto, regiao, 
MIN(preco_medio_revenda) AS preco_minimo, AVG(preco_medio_revenda) AS preco_medio,MAX(preco_medio_revenda) AS preco_maximo
FROM bc26-ed7-projeto-final.comercio_brasil.preco_combustiveis_2013_2022 
GROUP BY ano, produto, regiao ORDER BY ano DESC, preco_medio;

#os 50 maiores produtos valor por volume (dolar/volume) dos produtos nos 10 anos.
SELECT produto, sum(valor_dolar) as valor_total, sum(peso_liquido) as volume_total, 
(sum(valor_dolar)/sum(peso_liquido)) AS dolar_por_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2013-2022_tratada_ncm`
WHERE peso_liquido !=0 GROUP BY produto ORDER BY dolar_por_volume DESC LIMIT 50;

#insigh interresante, acho que fiz também por estado
#as via de transporte com de acordo com o volume exportado
SELECT meio_transporte, estado, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS valor_medio, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS volume_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm` 
GROUP BY 1, 2 ORDER BY meio_transporte, volume_total DESC;

#meses e anos ordenado pelo volume total importado - insight legal para ver em gráfico
SELECT ano, mes, sum(valor_dolar) as valor_total,  AVG(valor_dolar) AS valor_medio
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2013-2022_tratada_ncm` AS i
GROUP BY ano, mes ORDER BY valor_total DESC;

#valor total gasto em importação e o volume em relação a cada seção da Classificação Uniforme para Comercio Internacional em 2022
SELECT c.cuci_secao, SUM(im.valor_dolar) AS valor_total, SUM(im.peso_liquido) AS volume_total
FROM `bc26-ed7-projeto-final.comercio_brasil.imp_2012-2022_tratada_ncm` AS im
INNER JOIN `bc26-ed7-projeto-final.comercio_brasil.imp-exp-classificacoes` AS c
ON im.mercadoria=c.ncm 
WHERE ano=2022 GROUP BY 1 ORDER BY valor_total;

#meses com mais exportação em valor, junto com a media e o volume total e médio
SELECT mes, SUM(valor_dolar) AS valor_total, AVG(valor_dolar) AS media_valor, 
SUM(peso_liquido) AS volume_total, AVG(peso_liquido) AS media_volume 
FROM `bc26-ed7-projeto-final.comercio_brasil.exp_2013-2022_tratada_ncm`
GROUP BY mes ORDER BY valor_total;

